vacp2p/nim-libp2p

- libp2p/protobuf/minprotobuf.nim
The error in the code was that the `vsizeof(n)` was called
with a dummy zeroed variable, instead of the proper size of
the buffer. This resulted in an assertion failure when the
prefix length needs to be stored in more than 1 byte.
> Bugfix: Protobuf length prefix was assumed to be 1 byte

- libp2p.nimble
- libp2p/daemon/daemonapi.nim
- libp2p/protocols/secure/secio.nim
Fixes #39 
Reverting dde8c01448e0302c99c39fcd02ced88431a60d27 to proper exception handling. 
Note that `Exception` instead of `CatchableError` is used to emulate previous behavior of `raise getCurrentException()`.
> Fix finally use in daemonapi

- libp2p/muxers/mplex/lpchannel.nim
- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/secure/secio.nim
- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
- libp2p/transports/transport.nim
- tests/test.nim
- tests/testmplex.nim
Most logging should be trace level, which isn't enabled by default in neither debug nor release builds. I've replaced `debug` for `trace` to prevent unnecessary log pollution.
> set log level to trace - not enabled by default

- README.md
- examples/directchat.nim
- libp2p.nim
- libp2p/crypto/crypto.nim
- libp2p/crypto/ecnist.nim
- libp2p/crypto/ed25519/ed25519.nim
- libp2p/crypto/rsa.nim
- libp2p/crypto/secp.nim
- libp2p/protocols/protocol.nim
- libp2p/protocols/pubsub/rpc/message.nim
- libp2p/standard_setup.nim
- libp2p/switch.nim
- tests/pubsub/testfloodsub.nim
- tests/pubsub/testgossipsub.nim
- tests/pubsub/utils.nim
* Bugfix: Dialing an already connected peer may lead to a crash
* Introduced a standard_setup module allowing to instantiate
the `Switch` object in an easier manner.
* Added `Switch.disconnect(peer)`
* Trailing whitespace removed (sorry about polluting the diff)
> Fixes and tweaks related to the beacon node integration

- examples/directchat.nim
- libp2p/peerinfo.nim
- libp2p/standard_setup.nim
- libp2p/switch.nim
- tests/testidentify.nim
- tests/testinterop.nim
- tests/testpeerinfo.nim
* Refactor peerinfo to use openarrays instead of sequences.
* Fix tests and examples to use arrays instead of sequences.
* Add tests for lifetime.
> Add peer lifetime feature for PeerInfo.

- libp2p/switch.nim
- tests/pubsub/testgossipsub.nim
- tests/pubsub/utils.nim
- tests/testinterop.nim
- tests/testswitch.nim
Don't allow empty protocol dials and adding a `connect` method to substitute for empty dials.
NOTE: This is a breaking change, all empty protocol dials such as `switch.dial(peer)` should be changed for `switch.connect(peer)`.
> no empty proto dials

- libp2p.nimble
- libp2p/daemon/daemonapi.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
- libp2p/varint.nim
- libp2p/vbuffer.nim
- tests/testinterop.nim
- tests/testvarint.nim
Fix vsizeof() to properly handle signed types.
Add `sint32`, `sint64`, `sint` to use zigzag encoding for this types.
Add tests for signed varints.
Remove some casts to allow usage at compile time.
> Signed variable integers fixes.

- libp2p/muxers/mplex/coder.nim
Use `readExactly` instead of `read`, because `read` doesn't guarantee that all the required bytes will be read.
> Read all bytes

- libp2p/muxers/mplex/coder.nim
- libp2p/muxers/mplex/mplex.nim
- tests/testmplex.nim
This currently doesn't work due to a possible bug in `read` that never reads the last few bytes. @cheatfate
> add jitter tolerance to mplex

- libp2p/crypto/crypto.nim
- libp2p/muxers/mplex/lpchannel.nim
- libp2p/muxers/mplex/mplex.nim
- libp2p/protocols/identify.nim
- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/messages.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
- libp2p/protocols/secure/noise.nim
- libp2p/protocols/secure/secio.nim
- libp2p/protocols/secure/secure.nim
- libp2p/utility.nim
Since selecting chronicles log levels for each module is not possible I made  traces less verbose following @arnetheduck suggestion, and basically dump just a small slice of the array/string begin and end.
cc @stefantalpalaru
> Less verbose traces

- libp2p/connection.nim
- libp2p/multistream.nim
- libp2p/muxers/mplex/lpchannel.nim
- libp2p/muxers/mplex/mplex.nim
- libp2p/protocols/identify.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/secure/secure.nim
- libp2p/stream/bufferstream.nim
- libp2p/stream/chronosstream.nim
- libp2p/stream/lpstream.nim
- libp2p/switch.nim
- libp2p/transports/transport.nim
- tests/testinterop.nim
- tests/testmplex.nim
- tests/testswitch.nim
Properly cleanup the underlying bufferstream when closing the lpchannel.
Fixes #115.
> close underlying bufferstream in lpchannel

- libp2p.nimble
- libp2p/connection.nim
- libp2p/protocols/secure/secure.nim
- libp2p/stream/bufferstream.nim
- just BufferStream and Connection are tracked, for now
- flag checking is enforced more strictly in close(), since it became clear that instances are closed multiple times
The two metrics in Grafana, for the bootstrap node, while running eth2_network_simulation and starting/stopping an external node a couple of times:
Weird behaviour:
- initial mismatch: we're starting with 30 Connection instances, but only 25 BufferStream ones. Early leak?
- strange inversion after starting the external node the first time: why are there more BufferStream instances than Connection ones?
- Connection leak after killing the external node: 10 Connection instances were not closed
- large number of connections created the second time the external node was started: why are we opening 10 Connection and …
> add stream metrics

- libp2p.nimble
As of `2b823bde68cfb5efbe145945e8c17593f44eda5a` this is required due to https://github.com/status-im/nim-secp256k1/issues/20
> Require Nim v1.2.0 or higher

- README.md
It's a minor issue - but just wanted to bring up that the following links in the root README lead to a 404. This was because the README was pointing to a `doc/` folder instead of `docs/`. The respective directory changes were made for the following links: 
- API.md
- GETTING_STARTED.md
- GO_DAEMON.md
> Fixed typo in link resulting in 404

- libp2p/peerinfo.nim
they mess with debug prints and logging (same reason why $(seq) doesn't
print them)
> avoid newlines in $

- libp2p/standard_setup.nim
- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
- libp2p/transports/transport.nim
in order to avoid failures when restarting the process while the OS is
keeping open sockets from previous runs
> newTransport(): add "TransportFlags" param

- libp2p/errors.nim
- libp2p/stream/chronosstream.nim
- libp2p/transports/tcptransport.nim
- tests/helpers.nim
- tests/pubsub/testfloodsub.nim
- tests/pubsub/testgossipinternal.nim
- tests/pubsub/testgossipsub.nim
- tests/testidentify.nim
- tests/testmplex.nim
- tests/testmultistream.nim
- tests/testnoise.nim
- tests/testpeerinfo.nim
- tests/testswitch.nim
- tests/testtransport.nim
for now, chronos.AsyncStream is not used to provide any features on top
of chronos.Stream, so in order to simplify the code, chronosstream can
be used directly.
In particular, the exception handling is broken in the current
chronosstream - opening and closing the stream is simplified this way as
well.
A future implementation that actually takes advantage of the AsyncStream
features would wrap AsyncStream instead as a separate lpstream
implementation, leaving this one as-is.
> use stream directly in chronosstream

- libp2p/errors.nim
- libp2p/muxers/mplex/lpchannel.nim
- libp2p/muxers/mplex/mplex.nim
This was one bit I didn't fix during allFutures triage and it triggers test failures often still
> Properly track and close mplex handlers

- libp2p/connection.nim
- libp2p/multistream.nim
- libp2p/muxers/mplex/coder.nim
- libp2p/muxers/mplex/lpchannel.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/secure/noise.nim
- libp2p/protocols/secure/secio.nim
- libp2p/stream/chronosstream.nim
- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
- tests/pubsub/testgossipinternal.nim
- tests/testinterop.nim
Some of these are maybe too aggressive, but in return, they'll log
their exception - more refactoring needed to sort this out - right now
we get crashes on unhandled exceptions of unknown origin
* during connection setup
* while closing channels
* while processing pubsubs
> handle a few exceptions

- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
Mixing connection stoppage and transport stoppage leads to deadlock which manifests itself when tracking incoming connections.
This also fixes transport not tracking incoming connections.
> Track all connections

- libp2p/transports/tcptransport.nim
- libp2p/transports/transport.nim
- tests/testmplex.nim
Further cleanup of ownership and connection tracking. Transport should track incoming StreamTransports.
> don't track Connection, track StreamTransport

- libp2p/muxers/mplex/lpchannel.nim
- libp2p/muxers/mplex/mplex.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/secure/noise.nim
- libp2p/protocols/secure/secure.nim
- libp2p/stream/bufferstream.nim
- libp2p/stream/chronosstream.nim
- libp2p/stream/lpstream.nim
- libp2p/transports/tcptransport.nim
- tests/testmplex.nim
- tests/testnoise.nim
- tests/testswitch.nim
NOTE: To help uncluter this PR further, #178 and #175 should be merged first.
This is mostly a backport of the work started in #169, but without other changes concerning streams and incoming connections tracking, which is coming in a separate PR. This mostly fixes Mplex and LPChannel related issues. 
In particular there are number of issues that are fragile in the current implementation which leads to potential leaks, dangling resources and race conditions.
This PR contains:
- Fixes for properly closing and disposing of channels
- Fixes resource cleanup in mplex
- Simplifies and fixes half-closed functionality in LPChannel
- This required re-adding a write lock, because otherwise some messages could be interleaved, which was made evident by the close functionality
- Established proper …
> Half closed

- libp2p/protocols/pubsub/gossipsub.nim
This means we can use it from other protocols that inherit GossipSub. Otherwise,
a lot of internal state (heartbeat lock etc) doesn't get initialized properly.
See https://github.com/status-im/nim-waku/pull/19#issuecomment-635786640 for full context.
> Make GossipSub initPubSub method public

- libp2p/connection.nim
- libp2p/multistream.nim
- libp2p/muxers/mplex/coder.nim
- libp2p/muxers/mplex/lpchannel.nim
- libp2p/muxers/mplex/mplex.nim
- libp2p/muxers/muxer.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
- libp2p/protocols/secure/noise.nim
- libp2p/protocols/secure/secio.nim
- libp2p/protocols/secure/secure.nim
- libp2p/stream/bufferstream.nim
- libp2p/stream/chronosstream.nim
- libp2p/stream/lpstream.nim
- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
- tests/helpers.nim
- tests/pubsub/testfloodsub.nim
- tests/pubsub/testgossipinternal.nim
- tests/pubsub/testgossipsub.nim
- tests/testbufferstream.nim
- tests/testinterop.nim
- tests/testmplex.nim
- tests/testmultistream.nim
- tests/testnoise.nim
- tests/testpeerinfo.nim
- tests/testswitch.nim
This is a continuation of #187 (🍿), which got a bit unmanageable. 
Kind request, lets keep this on topic.
Bellow is the rationale as described in the original PR.
--------------------
This PR introduces some sane exception handling with the following rationale:
- Exceptions are polymorphic, use that to your advantage, don't overspecialize your exception handling code unless it's absolutely necessary
- Exceptions bubble up, that's by design, don't try to hide them, it will blow up in your face later on
- Exceptions flow is akin to a tree, where the leafs are exception originators and the root is where the exception eventually converges
- the most generic handler should be at the root of the tree
- more specialized exception handlers can be installed at different levels, depending on the …
> Resource cleanup

- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
Similar to https://github.com/status-im/nim-libp2p/pull/193 but doing it for all methods to avoid this issue in PubSub in the future. Got hit by this behavior again in rpcHandler and took me a while to figure out.
See https://github.com/oskarth/nim-private-method-skipping-case/ for minimal repro
> Make methods in FloodSub, GossipSub public

- libp2p/muxers/mplex/mplex.nim
- libp2p/protocols/identify.nim
- libp2p/protocols/secure/noise.nim
- libp2p/protocols/secure/secure.nim
- libp2p/stream/bufferstream.nim
- libp2p/stream/chronosstream.nim
- libp2p/stream/lpstream.nim
- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
- tests/pubsub/testgossipsub.nim
- tests/testbufferstream.nim
- tests/testidentify.nim
- tests/testmultistream.nim
- tests/testnoise.nim
- tests/testtransport.nim
Consolidate reading in lpstream. Different stream implementations only need to implement the `readOnce` method, the remaining routines `readExactly`, `readLine`, etc, are all implemented once in `LPStream` as a proc (no dynamic dispatch required), including for `BuffeStream`. This avoids duplicating the same logic for each stream type.
> consolidate reading in lpstream

- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/mcache.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/message.nim
- libp2p/protocols/pubsub/rpc/messages.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
- libp2p/standard_setup.nim
- tests/pubsub/testgossipinternal.nim
- tests/pubsub/testmcache.nim
- tests/pubsub/testmessage.nim
* don't send public key in message when not signing (information leak)
* don't run rebalance if there are peers in gossip (see #242)
* don't crash randomly on bad peer id from remote
> allow message id provider to be specified

- libp2p/multistream.nim
- libp2p/muxers/mplex/coder.nim
- libp2p/muxers/mplex/lpchannel.nim
- libp2p/muxers/mplex/mplex.nim
- libp2p/muxers/muxer.nim
- libp2p/peerinfo.nim
- libp2p/protocols/identify.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/secure/noise.nim
- libp2p/protocols/secure/secure.nim
- libp2p/stream/bufferstream.nim
- libp2p/stream/lpstream.nim
- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
- tests/testmplex.nim
- tests/testnoise.nim
This PR improves resource cleanup and reduces the number of `LPChannel`'s  in use as well as adds `Cancelation` support.
> Cleanup resources

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- tests/pubsub/testgossipinternal.nim
* gossipsub is a function of subscription messages only
* graft/prune work with mesh, get filled up from gossipsub
* fix race conditions with await
* fix exception unsafety when grafting/pruning
* fix allowing up to DHi peers in mesh on incoming graft
* fix metrics in several places
> clean up mesh handling logic

- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- tests/pubsub/testfloodsub.nim
- tests/pubsub/testgossipinternal.nim
- tests/pubsub/testgossipsub.nim
Remove the excessive use of `string` and `id` in favor of straight using `PubSubPeer` `ref` type.
Removes the need to resolve peers from `g.peers`
> PubSubPeer tables refactor

- libp2p/peerinfo.nim
- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/message.nim
- tests/pubsub/testgossipinternal.nim
- tests/pubsub/testmessage.nim
Quoting @oskarth 
> Am I reading it right that we currently don't have linearly increasing seqno in PubSub? https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/rpc/message.nim#L65-L66 It seems like it is picking a random set of bytes here. This seems different from https://github.com/libp2p/specs/blob/master/pubsub/README.md#the-message
Fixes
> Fix gossip messages seqno according to spec

- libp2p/crypto/crypto.nim
- libp2p/multiaddress.nim
- libp2p/peerid.nim
- libp2p/protobuf/minprotobuf.nim
- libp2p/protocols/identify.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
- libp2p/protocols/secure/noise.nim
- tests/testminprotobuf.nim
Transition from the result of `bool` to` Result [bool] `, so that now invalid messages and missing values can be distinguished.
> Minprotobuf refactoring 2

- README.md
- libp2p/muxers/mplex/mplex.nim
- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
Rationale: we can't handle that many metric samples on our remote servers.
```bash
stefan@master-01.aws-eu-central-1a.nimbus.test:~$ curl -sS localhost:9300/metrics | grep -vE '^(#|$)' | wc -l
9064
```
> put expensive metrics under a Nim define

- libp2p/protocols/pubsub/pubsubpeer.nim
Every Chronicles log record has an existing `msg` property matching
the static string supplied in the log statement. Thus, it's currently
not possible to use `msg` as the name of a user property:
https://github.com/status-im/nim-chronicles/issues/86
> `msg` is a reserved property name in Chronicles

- libp2p/peerinfo.nim
- libp2p/protocols/secure/noise.nim
- libp2p/switch.nim
- tests/testpeerinfo.nim
- tests/testswitch.nim
* peerinfo -> peerid
* include connection direction in event
* check connection status after event
* lock connmanager lookup also when dialling peer
* clean up un-upgraded connection when upgrade fails
* await peer eventing
> peer hooks -> events

- libp2p/crypto/ecnist.nim
- libp2p/crypto/ed25519/ed25519.nim
- libp2p/crypto/rsa.nim
This PR + https://github.com/status-im/nim-secp256k1/pull/24 fixes #289 and #290.
> Use constant-time comparison for keys and signatures.

- libp2p/connmanager.nim
- libp2p/muxers/mplex/mplex.nim
- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/peertable.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/message.nim
- libp2p/protocols/secure/secure.nim
- libp2p/standard_setup.nim
- libp2p/stream/chronosstream.nim
- libp2p/stream/lpstream.nim
- libp2p/switch.nim
- tests/pubsub/testfloodsub.nim
- tests/pubsub/testgossipinternal.nim
- tests/pubsub/testgossipsub.nim
- tests/pubsub/testmessage.nim
- tests/pubsub/utils.nim
- tests/testinterop.nim
- tests/testswitch.nim
- tests/testtransport.nim
Move pubsub out of switch and pass the switch into pubsub to allow it manage connections internally
TODO:
- peer lifetime events to properly trigger `subscribePeer`/`unsubscribePeer`
> Rework pubsub

- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsub.nim
...by making subscribeTopic synchronous, avoiding a peer table lookup
completely.
rebalanceMesh will be called a second later - it's fine
> avoid crash when subscribe is received

- libp2p/stream/bufferstream.nim
mplex backpressure handling deadlocks with something, this works around it for NBC's purposes - next step would be to reduce bufferstream size to 1 and continue digging
> work around bufferstream deadlock

- libp2p/switch.nim
when identify is run on incoming connections, the connmanager tables are
updated too late for incoming connections to properly be handled
this is a quickfix that will eventually need cleaning up
> work around race conditions between identify and other protocols

- libp2p/protocols/pubsub/pubsub.nim
`send` can raise exceptions that together with asyncCheck will
crash NBC
> work around send that may raise

- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/messages.nim
- libp2p/stream/bufferstream.nim
- tests/pubsub/testgossipinternal.nim
This is one example of how the deadlock in gossipsub can be avoided:
by making send a non-failing operation and dealing with send errors inside send. In particular, since `send` and `PubSubPeer` is responsible for setting up the send connection, it's also reasonable that it should be responsible for sending the initial subscription message to the other peer: this would likely resolve the problem that @zah was experiencing. To do that, `PubSub` needs to become aware that a new send connection has been opened over which the list of subscribed topics must be sent - for example through a callback or event.
It would then be natural that PubSubPeer also cleans up after itself - this would make gossipsub more independent in general and it wouldn't have to rely on connection events and NBC (or …
> avoid send deadlock by not allowing send to block

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/peertable.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/rpc/message.nim
* simplify gossipsub heartbeat start / stop
* avoid alloc in peerid check
* stop iterating over seq after unsubscribing item (could crash)
* don't crash on missing private key with enabled sigs (shouldn't happen
but...)
> small cleanups & docs

- libp2p/protocols/pubsub/rpc/messages.nim
- libp2p/switch.nim
if the connection is already closed (because the remote closes during
identfiy for example), an exception would be raised which would leave
the connection in limbo, beacuse it would not go through the rest of
internalConnect.
Also, if the connection is already closed, the disconnect event would be
scheduled before the connect event :/
> fix connection event order when connection dies early

- libp2p/protocols/pubsub/timedcache.nim
- tests/pubsub/testtimedcache.nim
it turns out (in NBC) a heap is sufficiently slow becuase of all the
deletes that it makes more sense to go with a linked list
> fix poor performance in LRU cache

- libp2p/muxers/mplex/lpchannel.nim
- libp2p/muxers/mplex/mplex.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/stream/bufferstream.nim
- libp2p/stream/connection.nim
- libp2p/stream/lpstream.nim
- tests/helpers.nim
- tests/testbufferstream.nim
- tests/testmplex.nim
This change modifies how the backpressure algorithm in bufferstream
works - in particular, instead of working byte-by-byte, it will now work
seq-by-seq.
When data arrives, it usually does so in packets - in the current
bufferstream, the packet is read then split into bytes which are fed one
by one to the bufferstream. On the reading side, the bytes are popped of
the bufferstream, again byte by byte, to satisfy `readOnce` requests -
this introduces a lot of synchronization traffic because the checks for
full buffer and for async event handling must be done for every byte.
In this PR, a queue of length 1 is used instead - this means there will
at most exist one "packet" in `pushTo`, one in the queue and one in the
slush buffer that is used to store incomplete reads.
* avoid byte-by-byte …
> refactor bufferstream to use a queue

- libp2p/connmanager.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
Noticed a few missing logscope topics, this makes output such as the following easier to grep etc.
```
TRC 2020-09-15 11:03:48.872+08:00 Pushing readQueue                          topics="bufferstream" tid=31676 s=16*zd2AuE:5f602f14dd0f40441adc6102 len=1
TRC 2020-09-15 11:03:48.872+08:00 pushed data to channel                     topics="mplex" tid=31676 m=16*zd2AuE:5f602f14dd0f40441adc60f5 channel=16*zd2AuE:5f602f14dd0f40441adc6102:5f602f14dd0f4
0441adc6101 msgType=MsgOut id=3 initiator=false size=1                                                                                                                                             
TRC 2020-09-15 11:03:48.872+08:00 waiting for data                           topics="mplex" tid=31676 m=16*zd2AuE:5f602f14dd0f40441adc60f5
TRC …
```
> Add logScope to connmanager and pubsubprotobuf

- libp2p/muxers/mplex/coder.nim
- libp2p/muxers/mplex/lpchannel.nim
- libp2p/muxers/mplex/mplex.nim
- libp2p/stream/bufferstream.nim
- libp2p/stream/chronosstream.nim
- libp2p/stream/connection.nim
- libp2p/stream/lpstream.nim
- tests/helpers.nim
- tests/pubsub/testfloodsub.nim
- tests/pubsub/testgossipinternal.nim
- tests/pubsub/testgossipsub.nim
- tests/testbufferstream.nim
- tests/testconnmngr.nim
- tests/testidentify.nim
- tests/testmplex.nim
- tests/testmultistream.nim
- tests/testnoise.nim
- tests/testswitch.nim
- tests/testtransport.nim
* remove send lock, write chunks in one go
* push some of half-closed implementation to BufferStream
* fix some hangs where LPChannel readers and writers would not always
wake up
* simplify lazy channels
* fix close happening more than once in some orderings
* reenable connection tracking tests
* close channels first on mplex close such that consumers can read bytes
A notable difference is that BufferedStream is no longer considered EOF
until someone has actually read the EOF marker.
> channel close race and deadlock fixes

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub10.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- tests/pubsub/testgossipinternal.nim
- tests/pubsub/testgossipinternal10.nim
When messages can't be sent to peer, we try to establish a send
connection - this causes messages to stack up as more and more unsent
messages are blocked on the dial lock.
* remove dial lock
* run reconnection loop in background task
> fix gossipsub memory leak on disconnected peer

- libp2p/muxers/mplex/lpchannel.nim
- libp2p/protocols/identify.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/stream/chronosstream.nim
- libp2p/stream/lpstream.nim
- libp2p/switch.nim
* add helper to read EOF marker after closing stream (else stream stay
alive until timeout/reset)
* don't assert on empty channel message
* don't loop when writing to chronos (no need)
> small fixes

- libp2p/muxers/mplex/lpchannel.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
- libp2p/stream/bufferstream.nim
To break a potential read/write deadlock, gossipsub uses an unbounded
queue for writes - when peers are too slow to process this queue, it may
end up growing without bounds causing high memory usage.
Here, we introduce a maximum write queue length after which the peer is
disconnected - the queue is generous enough that any "normal" usage
should be fine - writes that are `await`:ed are not affected, only
writes that are launched in an `asyncSpawn` task or similar.
* avoid unnecessary copy of message when there are no send observers
* release message memory earlier in gossipsub
* simplify pubsubpeer logging
> limit write queue length

- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/message.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
This helps protect against clients sending more data than they should
and thus getting penalized on topics that require anonymity
> reencode gossipsub messages with anonymization

- libp2p/protocols/pubsub/gossipsub10.nim
gossipsub.nim has control messages on trace but gossipsub10.nim had it on debug.
> saner logging

- libp2p/protocols/secure/secure.nim
As discussed in the previous meeting
> handle secure errors in readOnce (secure)

- libp2p.nimble
- libp2p/protocols/secure/secure.nim
@dryajov As discussed in the call, this is mostly temporary, I will review where to handle the exception better.
> avoid verbose EOF messages in readOnce(secure)

- libp2p/muxers/mplex/lpchannel.nim
- libp2p/muxers/mplex/mplex.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/secure/secure.nim
- libp2p/stream/bufferstream.nim
- libp2p/stream/chronosstream.nim
- libp2p/stream/connection.nim
- libp2p/stream/lpstream.nim
- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
This reverts commit 1de1d49223505a44535fa8835d1c0c65fc4c00fb.
The leak fix seems to turn the leak into deadlock which occasionally causes nbc to freeze when requesting blocks and similar issues - this needs more investigation before going in - it could potentially be the gossipsub 1.1 upgrade but that seems less likely since the lockups are related to fetching blocks.
Don't have a perfect repro, but syncing and reconnecting wifi make the symptoms show, including large differences between libp2p and nbc peer counts and sync requests that don't end for hours (even when they should time out)
> Revert "Channel leaks (#413)"

- libp2p/muxers/mplex/lpchannel.nim
- libp2p/stream/bufferstream.nim
- libp2p/stream/lpstream.nim
- tests/testbufferstream.nim
- tests/testmplex.nim
This PR does two things:
1. Disables concurrent `pushData` calls, which 1) break backpressure because at that point the async subsystem acts as a boundless buffer 2) adds unneeded complexity to the implementation, which has been a source of multiple issues that attempt to handle corner cases introduced by a  useless/faulty requirement.
2. Corrects the reset flow to handle the following cases:
- If a push was in progress but no reader is attached we need to pop the queue
- If a read was in progress without a push/data we need to push the Eof marker to notify the reader that the channel closed
- In all other cases, there should be a data to complete a read or enough room in the queue/buffer to complete a
push.
Here is a quick truth table to illustrate the cases:
State       | Q Empty  | Q …
> Don't allow concurrent pushdata

- libp2p/stream/lpstream.nim
- tests/testswitch.nim
Fixes the double read assert in BufferStream (credits to @cheatfate for suggesting this)
> allow concurrent closeWithEOF

- libp2p/connmanager.nim
- libp2p/stream/bufferstream.nim
- libp2p/switch.nim
- tests/testconnmngr.nim
- tests/testmplex.nim
- tests/testswitch.nim
It appears that the double read assert might be due to a race in connection setup - in the interplay of an ongoing connection setup and a disconnect. The main culprit appears to be releasing the dial lock too early, and not checking that the connection is still alive in the right places.
This PR attempts to fix the following:
- The dial lock is being released prematurely 
- The tests for a valid connection should happen before releasing the lock
- Connection manager should not allow closed connections to be stored
- Identifying a muxed connection should happen as early as possible
> Race in connection setup

- libp2p/muxers/mplex/coder.nim
- libp2p/muxers/mplex/lpchannel.nim
- libp2p/protocols/secure/noise.nim
- libp2p/protocols/secure/secure.nim
This avoids some unnecessary memory copying on the hot path of noise /
mplex, as well as getting rid of a few futures - profiling shows that
this is one of the main culprits of small memory allocations, which
makes sense - this is where gossip fan-out happens.
* fewer futures (and corresponding closures) when sending lpchannel
messages
* avoid data copies when encrypting and framing noise messages
* avoid copying tuple when reading noise data (poor c codegen)
* fix setting eof flag in secure read
> streamline socket read/write hot path

- .travis.yml
See https://github.com/status-im/nimbus-eth2/pull/2167
Trying to revivie ARM64 on Travis and we will reserve our Travis credits for that.
> Use Travis only for ARM64

- tests/testvarint.nim
Since Nim v1.2.8, casting an overflowing value to an `int64`, will correctly produce a `RangeError`.
Closes #483
> Fixing `RangeError` introduced in Nim v1.2.8

- libp2p/multiaddress.nim
- libp2p/stream/lpstream.nim
- libp2p/varint.nim
- libp2p/vbuffer.nim
* avoids multiple reallocations in writeLp
* simplifies varint implementation
* remove vbuffer.length (unused)
depends on https://github.com/status-im/nim-stew/pull/66
> use stew/leb128

- README.md
Currently, if you try clicking on the image in the README, it acts as though `libp2p.io` is some local url relative to the GitHub README url.
> fix invalid README hyperlink by adding https prefix

- README.md
Going off the [libp2p.nimble](https://github.com/status-im/nim-libp2p/blob/master/libp2p.nimble) file, it seems that nim version 1.2.0 is now being used, so I adjusted the README according, and removed the broken `<a>` tag.
> Update README to display correct nim version

- libp2p/connmanager.nim
- libp2p/protocols/secure/secure.nim
- libp2p/stream/connection.nim
- libp2p/stream/lpstream.nim
- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
- libp2p/utils/semaphore.nim
- tests/helpers.nim
- tests/testnative.nim
- tests/testsemaphore.nim
This PR adds inflight connection throttling for incoming connections. 
It includes:
- Adds an `upgraded` event to connections to signal when it has been upgraded/failed
- This is needed for incoming connections because the initiator controls the upgrade flow
- Incoming connection upgrade throttling to match how dial works and prevent them from taking up all the available slots
> Concurrent upgrades

- libp2p/peerstore.nim
- tests/testpeerstore.nim
This PR closes #498
It introduces a POC version of a Peer Store with Address Book, based on similar implementations in [go](https://github.com/libp2p/go-libp2p-peerstore) and [js](https://github.com/libp2p/js-libp2p/tree/master/src/peer-store).
The POC:
- Implements a simple AddressBook API to add, get, set and delete multiaddresses for peers
- Implements a simple PeerStore API to get and delete stored information for peers across all books (although the address book is the only one implemented so far)
- Allows clients to add their own listeners to be notified of peer store events. Each listener contains a number of handlers that are triggered on changes in the peer store. For POC purposes, I have only added a handler for multiaddr changes on a peer.
1. Gain consensus both on general …
> Address Book POC implementation

- libp2p/switch.nim
- libp2p/upgrademngrs/muxedupgrade.nim
- libp2p/upgrademngrs/upgrade.nim
This refactors the upgrade flow from the switch into its own module. This is the first step to allow multi-transport support.
> Split upgrade flow

- libp2p.nim
- libp2p/standard_setup.nim
- tests/pubsub/testgossipsub.nim
- tests/testinterop.nim
- tests/testswitch.nim
Note, as the title state, this removes secio usage and would `quit` if it's attempted to be used with `newStandardSwitch` - maybe quitting is a bit too drastic?
> Remove secio usage and cleanup exports

- tests/pubsub/testfloodsub.nim
Fixes #525
add coverage to unsubscribeAll and testing
> Revisit Floodsub

- libp2p/dial.nim
- libp2p/dialer.nim
- libp2p/standard_setup.nim
- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
- libp2p/transports/transport.nim
- libp2p/upgrademngrs/muxedupgrade.nim
- libp2p/upgrademngrs/upgrade.nim
- tests/testidentify.nim
- tests/testmplex.nim
- tests/testmultistream.nim
- tests/testnoise.nim
- tests/testswitch.nim
- tests/testtransport.nim
- Move dialing logic from switch to its own module
- Allow transports drive their own upgrade flow by exposing `upgradeIncoming` and `upgradeOutgoing`
TODO:
> Split dialer

- libp2p/stream/connection.nim
- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
Makes code compatible with
https://github.com/status-im/nim-chronos/pull/166 without requiring it.
> Fix minor exception issues

- .github/workflows/ci.yml
- libp2p/stream/connection.nim
- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
- tests/testbufferstream.nim
Merging latest master. 
There is a curious bug/issue, `doAssert` seems to raise a `ValueError` instead of an `AssertionError`?
> Merging latest master and possible bug?

- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/gossipsub/scoring.nim
- libp2p/protocols/pubsub/gossipsub/types.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
- libp2p/stream/lpstream.nim
- tests/pubsub/testgossipsub.nim
In `async` functions, a closure environment is created for variables
that cross an await boundary - this closure environment is kept in
memory for the lifetime of the associated future - this means that
although _some_ variables are no longer used, they still take up memory
for a long time.
In Nimbus, message validation is processed in batches meaning the future
of an incoming gossip message stays around for quite a while - this
leads to memory consumption peaks of 100-200 mb when there are many
attestations in the pipeline.
To avoid excessive memory usage, it's generally better to move non-async
code into proc's such that the variables therein can be released earlier
- this includes the many hidden variables introduced by macro and
template expansion (ie chronicles that does expensive …
> mem usage cleanups for pubsub

- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/stream/lpstream.nim
- tests/helpers.nim
* fix KeyError when updating metric of unsubscribed topic
* fix unsubscribe message not being sent to all peers causing them to
keep thinking we're still subscribed
* release memory earlier in a few places
> gossipsub: unsubscribe fixes

- docs/GETTING_STARTED.md
- libp2p/builders.nim
- libp2p/multistream.nim
- libp2p/muxers/muxer.nim
- libp2p/protocols/identify.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/secure/noise.nim
- libp2p/protocols/secure/plaintext.nim
- libp2p/protocols/secure/secio.nim
- libp2p/stream/bufferstream.nim
- libp2p/upgrademngrs/muxedupgrade.nim
- tests/helpers.nim
- tests/pubsub/testgossipinternal.nim
- tests/testbufferstream.nim
- tests/testconnection.nim
- tests/testidentify.nim
- tests/testmplex.nim
- tests/testmultistream.nim
- tests/testnoise.nim
A commit per function, easy to revert if needed. Deprecated old procs.
I'll update the examples more thoroughly in an other PR
My apologies to everybody using the libp2p :bowing_man: 
I've left a few newXXX :
- newRng
- newSwitch
- newStandardSwitch
- all new Errors
> Change newXXXX procs to XXXX.new

- libp2p/protocols/ping.nim
- tests/testping.nim
closes #567 
Simple ping protocol implemented.
This is a low level version (eg, you can launch a ping using the `ping` proc, and it will reply to ping), like the JS one
It would be possible to add more functionality :
- Waku keepalive seems to use a handler, the `newPing` function could take a handler without much issue if required EDIT: done
- In rust, it looks like the libp2p bundles a Handler which ping automatically
> add ping protocol

- libp2p/builders.nim
- libp2p/connmanager.nim
- libp2p/peerstore.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/switch.nim
- libp2p/upgrademngrs/upgrade.nim
- tests/testpeerstore.nim
- tests/testswitch.nim
Following #504 
Ref #537
This PR add a `PeerStore` to the `Switch`.
The PeerStore is still user-overridable to wrap it with other fields if needed (as done in Waku)
The connmanager's PeerEvent has a new type of event: `Identify`, which is triggered when the peer identifies (or `pushidentity`, in the future)
On identify, the peer informations are store inside the PeerStore through a `PeerEventHandler`
**Breaking change**
The `ConnEventHandler` & `PeerEventHandler` signatures changed: they now receive a `PeerInfo` instead of a `PeerID`
> Peer Store implement part II

- libp2p/muxers/mplex/lpchannel.nim
- libp2p/protocols/secure/secure.nim
- libp2p/stream/bufferstream.nim
- libp2p/stream/connection.nim
- libp2p/stream/lpstream.nim
- tests/helpers.nim
- tests/testswitch.nim
There is a typo in `test/helpers.nim` which made `checkTracker` useless. Fixing it broke a few tests
(nim doesn't have a "unused parameter" warning? seems like a super important warning)
> Fix trackers tests

- libp2p/builders.nim
Useful to advertise both an ipv4 & ipv6, for instance
> builder: add multiple local address support

- tests/testswitch.nim
Seen on #565 
Probably not the best way to solve it, but MacOS seem takes some time to close the stream on the receiving end, and thus the stream isn't closed quickly enough.
This PR solves it, as demonstrated here: https://github.com/status-im/nim-libp2p/runs/2887560022
> Fix flaky macos switch test

- libp2p/vbuffer.nim
The same as https://github.com/status-im/nim-libp2p/pull/600, but against `unstable` branch.
> make `isLiteral` compatible with ARC and ORC, take 2

- libp2p/stream/chronosstream.nim
- tests/helpers.nim
The current failures in macos are triggered by the `ChronosStreamTrackerName`, which is currently not tracked in every test.
Putting it here to see what breaks
> Track ChronosStream in test

- libp2p/switch.nim
The current way the switch is started is wrong, because the transport may take some time to `start` (it's async), but the switch assumes that the `t.ma` is valid and that the `t.running` is true without waiting for `start` to finish.
This can have some pretty bad consequence (for instance not starting the accept loop, as happens here https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnimbus-eth2%2Fmultibranch/detail/PR-2724/1/pipeline/), so merging against master.
By the way, I never understood why we returned the futures of the transport starting? I would remove it, but it would break API. So returning an empty seq
EDIT: not returning and empty seq anymore to allow caller to check how many transports start to fail. But we could find a better way I'm sure (eg returning the number of …
> Fix transport's switch start

- tests/testidentify.nim
- tests/testswitch.nim
This test failed because the order in which the elements of a hashset are added to a seq is non-deterministic. It accidentally worked in Nim 1.2.6, but not in 1.4.8.
> Fixes failing peer store test in Nim 1.4.8

- .github/workflows/ci.yml
#603 broke the unstable auto bump, because `ci` was not launched on the unstable branch anymore (we relied on the "unstable merge" PR to run the unstable's CI)
Thus I'm re-enabling the CI on the unstable branch, even though that will duplicate some CI runs on unstable, we merge to unstable sporadically enough that it should not be an issue, hopefully.
> Fix unstable autobump

- libp2p/protocols/pubsub/gossipsub/behavior.nim
Currently, the `BackoffSlackTime` is taken into account to refuse incoming `grafts`. 
This is an issue, because a peer may send us a graft as soon as the backoff time is finished, not knowing about this 2 seconds delay, and we'll end up refusing his graft.
This PR fixes that by substracting two time the BackoffSlackTime on incoming graft request. The first time to fix the issue, and a second time to avoid race conditions.
> Fix gossipsub incoming graft backoff

- libp2p/crypto/crypto.nim
- libp2p/crypto/ecnist.nim
- libp2p/crypto/ed25519/ed25519.nim
- libp2p/crypto/rsa.nim
- libp2p/crypto/secp.nim
- libp2p/peerid.nim
- libp2p/peerinfo.nim
- libp2p/protocols/pubsub/rpc/message.nim
- libp2p/protocols/secure/noise.nim
- libp2p/protocols/secure/secio.nim
- tests/testcrypto.nim
- tests/testecnist.nim
- tests/tested25519.nim
- tests/testidentify.nim
- tests/testpeerid.nim
- tests/testpeerinfo.nim
- tests/testrsa.nim
Last name was confusing, eg: https://github.com/status-im/nim-libp2p/pull/610#discussion_r699668952
Also avoided to do
```nim
privateKey
.getPublicKey()
```
Which can be confusing
> Rename getKey -> getPublicKey

- .github/workflows/ci.yml
bump libp2p-go-daemon to `124530a3` (v0.3.0 is broken on MacOS)
> Fix macos go-daemon CI

- libp2p.nimble
- libp2p/muxers/mplex/lpchannel.nim
Follow up #607 
Fix typo in CT flag: -d:li**p**p2p_network_protocols_metrics
> Fix muxer bandwidth typo

- libp2p.nimble
- libp2p/dialer.nim
- libp2p/nameresolving/nameresolver.nim
- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
- libp2p/transports/transport.nim
- libp2p/transports/wstransport.nim
- tests/testnameresolve.nim
- tests/testswitch.nim
- tests/testwstransport.nim
Follow up of #580
Closes #571
TLDR of current DNS state:
Actually resolving multiaddress can be tricky in our infra, because:
- For WSS, we need to keep the original hostname
- We would like to deduplicate resolved addresses to avoid redundant dial
- But in the case of WSS, a different hostname/ip pair can have a different meaning, and we should dial both
- We need to keep the resolving in the dialer (instead of the transport), because `dnsaddr` could resolve into different transports
So it seems that our only option is to resolve in the dialer, deduplicate on `hostname/ip` pair (or not deduplicate at all), and give the hostname to the transport.
Is there a better option?
> Integrate dns resolving

- libp2p/muxers/mplex/mplex.nim
- libp2p/upgrademngrs/muxedupgrade.nim
closes #635 
The current "connection management" makes this operation a bit painful, because it's hard to pass data around layers (`libp2p_peers_identity` needs the shortAgent on "layer 0" (chronosstream), but the shortAgent is given on identify which is "layer 4" (chronosstream -> secureconn -> muxer -> identify), so we have to copy it around everywhere)
So dirty fix for now, hopefully will improve with better conn management
> Short agent fix

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/types.nim
- tests/pubsub/testgossipsub.nim
Closes #626
This PRs adds a cache for currently validated message, and if a peer sends us a message which we are validating, we'll avoid forwarding him once validation is complete.
This also supersedes #625, because the source peer is put by default in the said cache.
cc @arnetheduck
> Gossipsub: don't send to peers seen during validation

- .github/workflows/multi_nim.yml
- libp2p.nimble
Will be faster, and the interops tests are flaky right now (because of go-libp2p-daemon)
> CI Multi nim: only test slim

- libp2p/peerstore.nim
- tests/testidentify.nim
Adding received signed peer record from `identify` to new peer book according to #647 and as an increment towards GossipSub Peer Exchange.
(Note: I notice [the go implementation](https://github.com/libp2p/go-libp2p-peerstore/blob/master/pstoreds/addr_book.go#L316) stores the marshalled SPR. Perhaps we should consider doing the same, if it's significantly easier to forward as such on PRUNE? I prefer the current way (with `Envelope` object) though.)
> Add SPR from identify to new peer book

- libp2p/transports/wstransport.nim
nim-websock can throw a few different exceptions which previously crashed the entire accept loop
I think I got them all
Exception tracking would be nice
> Handle websock exceptions in handle

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/gossipsub/types.nim
- tests/pubsub/testgossipsub.nim
- tests/pubsub/utils.nim
This is an alternative to https://github.com/status-im/nimbus-eth2/pull/3025
It allows applications to choose a different backoff when we unsubcribe from a gossipsub topic.
Currently, if you unsubscribe - resubscribe from a topic in less than `backoff` seconds, all of your peers that were previously in your mesh are in your backoff, and won't allow you to graft them back. Setting the `unsubcribeBackoff` to a lower value allows you to alleviate this issue.
Note that it should still be >0 seconds, or some implementations (including ours) will ignore it. However, if it's less than `BackoffSlackTime` (2 seconds), it will effectively be a 0 seconds backoff.
It should not be an issue to have a 0 seconds backoff, since you're unsubscribed and peers should not attempt to graft you until you resub …
> Customizable gossipsub backoff on unsubscribe

- examples/directchat.nim
- examples/helloworld.nim
- examples/tutorial_1_connect.md
- examples/tutorial_2_customproto.md
- libp2p/switch.nim
- tests/testidentify.nim
- tests/testinterop.nim
- tests/testnoise.nim
- tests/testswitch.nim
The proc `start` returned a seq of futures that was mean to be awaited by the caller. However, the start proc itself awaited each Future before returning it, so the ceremony requiring the caller to await the Future, and returning the Futures themselves, was unnecessary.
Remove `switch.start` return type (implicit `Future[void]`)
Update tutorials and examples to reflect the change.
> fix: remove returned Futures from switch.start

- libp2p/protobuf/minprotobuf.nim
This hardens the length check in `ProtoBuffer.finish` to account for
passed `options`.
> harden `ProtoBuffer.finish()` assert

- libp2p/crypto/ecnist.nim
- tests/testecnist.nim
Currently, `ecnist`'s `toBytes` and `getBytes` methods operate only on
properly initialized keys. If an un-initialized key is given, an
`IndexError` may be raised if the key's `xlen` / `qlen` property is
larger than the maximum buffer size. This patch hardens those functions
to report a proper error in that case.
Note that the library functions called by `init` and `initRaw` already
reject data that does not have the expected length, so these new checks
should not be reachable in practice.
> harden `ecnist` byte export against uninitialized key

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/types.nim
- tests/pubsub/utils.nim
My number of typo per commit is through the roof
> Typo: s/unsubcribeBackoff/unsubscribeBackoff

- libp2p/protocols/pubsub/gossipsub.nim
Related to #641
When a peer unsub without pruning before, we currently keep it "in mesh" in the scoring mechanism, which create issues
> Score correctly on mesh peer unsub

- libp2p/transports/wstransport.nim
by mapping AsyncStreamIncompleteError to an EOF
> Fix websocket EOF reading exception

- libp2p/protocols/pubsub/errors.nim
- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/rpc/message.nim
- tests/pubsub/testfloodsub.nim
- tests/pubsub/testgossipinternal.nim
- tests/pubsub/testgossipsub.nim
- tests/pubsub/testmcache.nim
- tests/pubsub/testmessage.nim
- tests/pubsub/utils.nim
Closes: #642.
Changes the return type of the msgIdProvider to `Result[MessageID, string]` so that message id generation can fail.
String error type was chosen as this `msgIdProvider` mainly because the failed message id generation drops the message and logs the error provided. Because `msgIdProvider` can be externally provided by library consumers, an enum didn’t make sense and a object seemed to be overkill. Exceptions could have been used as well, however, in this case, Result ergonomics were warranted and prevented wrapping quite a large block of code in try/except.
The `defaultMsgIdProvider` function previously allowed message id generation to fail silently for use in the tests: when seqno or source peerid were not valid, the message id generated was based on a hash of the message …
> feat: allow msgIdProvider to fail

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- tests/pubsub/testgossipsub.nim
When we are subscribed to a topic, we currently only try to publish to peers in a mesh.
If we have backing off peers, we don't do anything with them, even though we could publish to them.
This PR fixes that, but trying to top up to `d` with peers from the fanout
> GS: Publish to fanout when mesh unhealthy

- .github/workflows/ci.yml
- .github/workflows/multi_nim.yml
The version of the go daemon we use doesn't work with recent go versions
I've disabled the daily job until this hit master
> Pin go version in CI

- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/gossipsub/scoring.nim
- libp2p/protocols/pubsub/gossipsub/types.nim
- libp2p/protocols/pubsub/timedcache.nim
- libp2p/utils/heartbeat.nim
- tests/pubsub/testgossipsub2.nim
- tests/testheartbeat.nim
- tests/testnative.nim
We were lacking implementation for two parameters that changed the scoring completely:
decayInterval: was pegged to the heartbeat, so the decay speed was wrong
meshMessageDeliveriesWindow: every peer was gaining score for delivering, even if it was 5 minutes late
Also added a little check, to avoid peers sending us duplicate, hoping to get more points
> Gossipsub scoring fixes

- libp2p/builders.nim
- libp2p/dial.nim
- libp2p/dialer.nim
- libp2p/multiaddress.nim
- libp2p/protocols/relay.nim
- libp2p/switch.nim
- tests/testinterop.nim
- tests/testnative.nim
- tests/testrelay.nim
A simple way to make it work at the moment:
```nim
proc main() {.async, gcsafe.} =
let
rng = newRng()
src = newStandardSwitch(rng=rng)
rel = newStandardSwitch(rng=rng)
address = MultiAddress.init("/ip4/127.0.0.1/tcp/0").tryGet()
addressRelay = MultiAddress.init("/ip4/127.0.0.1/tcp/0/p2p-circuit").tryGet()
dst = SwitchBuilder
.new()
.withRng(rng)
.withAddresses(@[ address, addressRelay ])
.withTcpTransport()
.withMplex()
.withNoise()
.build()
pingProtocol = Ping.new(rng=rng)
relaySrc = Relay.new(src, false)
relayRel = Relay.new(rel, true)
relayDst = Relay.new(dst, false)
src.mount(relaySrc)
rel.mount(relayRel)
dst.mount(relayDst)
dst.mount(pingProtocol)
src.transports &= RelayTransport.new(relaySrc)
((Dialer)src.dialer).transports = src.transports
dst.transports &= …
```
> Circuit relay v1

- libp2p/protocols/pubsub/gossipsub.nim
the number of peers sent to is returned from the function - the caller
can log this, if need be
> lower log level of no-peers message

- libp2p/builders.nim
- libp2p/switch.nim
- libp2p/upgrademngrs/muxedupgrade.nim
- tests/testnoise.nim
A simple change in the way to store `MuxerProvider` to remove the randomness of the Table (it could have been an OrderedTable, but I think it's a bit silly to use that for a maximum of two elements).
Now the first muxer added in the switch builder is always the one used/tried first.
> Replace table by seq for storing muxers

- libp2p/crypto/curve25519.nim
- libp2p/dial.nim
- libp2p/dialer.nim
- libp2p/peerid.nim
- libp2p/protocols/secure/noise.nim
- libp2p/protocols/secure/secio.nim
- libp2p/protocols/secure/secure.nim
- libp2p/switch.nim
- libp2p/transports/transport.nim
- libp2p/upgrademngrs/muxedupgrade.nim
- libp2p/upgrademngrs/upgrade.nim
- tests/testnoise.nim
- tests/testswitch.nim
Useful when connecting to a noise peer based on IP address alone
> allow connection to a peer with unknown PeerId

- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- tests/pubsub/testgossipinternal.nim
Since this was introduced, nimbus got better peer management, and will eventually kick a useless peer (ie not supporting GS) if required
The current behavior is obviously wrong, because nimbus & waku won't peer with light clients not supporting GS for instance
> Keep connection alive when peer doesn't support pubsub

- libp2p/muxers/mplex/lpchannel.nim
- libp2p/muxers/mplex/mplex.nim
- libp2p/muxers/yamux/yamux.nim
- libp2p/stream/bufferstream.nim
- libp2p/stream/lpstream.nim
- tests/testmplex.nim
- tests/testyamux.nim
Solve #755, it should raise these new errors instead of only LPStreamEOFError
```
X     | Remote reset       | Local reset         | Remote close              | Local close         | Connection down    
Read  | LPStreamResetError | LPStreamClosedError | LPStreamRemoteClosedError | Works               | LPStreamConnDownError
Write | LPStreamResetError | LPStreamClosedError | Works                     | LPStreamClosedError | LPStreamConnDownError
```
> Specify EOF error

- .github/workflows/bumper.yml
Similar to nimbus: https://github.com/status-im/nimbus-eth2/pull/3916
Will run CI on waku & codex for each unstable push on libp2p
Also opens the possibility to run a few nodes of each project with libp2p's unstable at all times, which is very useful
> Add codex & waku to autobump

- README.md
Lodestar is switching from `js-libp2p/0.36.2` to `lodestar/version`. Document how to collect metrics on Lodestar peers following that scheme. https://github.com/status-im/nimbus-eth2/issues/4106
> add `lodestar` to known lib p2p agents documentation

- examples/circuitrelay.nim
- libp2p/multiaddress.nim
- libp2p/peerinfo.nim
- libp2p/switch.nim
- tests/testidentify.nim
- tests/testnoise.nim
- tests/testpeerinfo.nim
- tests/testrelayv2.nim
closes #450, #429, #556
`switch.peerInfo.addrs` is now read-only
To modify addresses, you should use a mapper instead
It may break stuff, because `switch.peerInfo.addrs` is empty before `switch.start()` (previously it was not empty, but potentially invalid, which seems worst)
> Allow public address mapping

- libp2p/crypto/minasn1.nim
- libp2p/multiaddress.nim
- libp2p/peerid.nim
- libp2p/protobuf/minprotobuf.nim
- libp2p/vbuffer.nim
Beside not being compatible with orc, they can introduce weird / unsafe behaviors.
They seemed to be used only in places with a few bytes (worst case being private keys around 256 bytes), so I doubt we'll see any performance regression, but I have a branch with `when defined(shallowCopy)` everywhere ready if that's the case
> Remove shallow copies

- tests/helpers.nim
- tests/pubsub/testfloodsub.nim
- tests/pubsub/testgossipsub.nim
- tests/testidentify.nim
- tests/testmplex.nim
- tests/testswitch.nim
It's flaky
We should aim to remove as many sleepAsync as possible, as they are generally synonyms with flaky tests. Exception being tests actually based on time
> Remove sleepAsync from tests/testswitch

- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/gossipsub/scoring.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
Added `libp2p` topic to the chronicles topics list. For consistency and because this is necessary to filter out all the logs with `-d:"chronicles_disabled_topics=libp2p"`.
> Add libp2p label to chronicles log topics

- .github/workflows/multi_nim.yml
Since `orc` became the default, we were not running CI with refc on devel
> Daily CI: run devel with refc

- .github/actions/install_nim/action.yml
- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .github/workflows/multi_nim.yml
This PR creates a reusable `install_nim` action that builds nim using the NBS
It will cache the built nim version for the specific arch & os.
The daily CI will run on `unstable`, delete those cached build, and re-create them every day (to make sure we have up to date nim versions)
If this action works well, it will be moved to the NBS, to be reused by other repos
Also note, only one CI run is allowed per PR now, the rest will be cancelled.
> Reuseable install_nim action

- examples/tutorial_2_customproto.nim
- examples/tutorial_3_protobuf.nim
- examples/tutorial_5_discovery.nim
- examples/tutorial_6_game.nim
- libp2p/multistream.nim
- libp2p/protocols/protocol.nim
- tests/testmultistream.nim
Each protocol can specify a maximum number of (inbounds) streams per Peer (not connection!). Above that, new streams will be closed directly.
This default to 10, could be finer tuned for each libp2p protocol, but I think it's pretty good default
> Limit number of streams per protocol per peer

- libp2p/muxers/mplex/lpchannel.nim
- libp2p/muxers/mplex/mplex.nim
While closing an individual channel (e.g., due to cancellation) there is a race where we may still receive messages before we deallocated the channel. Handle that case gracefully to avoid closing down the entire underlying connection (which also holds all other active channels).
> Avoid closing connection on channel EOF

- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
This PR fixes a subtle race condition that I discovered while working on https://github.com/status-im/nim-libp2p/pull/807. Since 807 renders the upgrade "faster" (less callback and asyncSpawn etc), it's highlights some bugs, which is cool
I think this race condition can also happen without 807.
1 - A peer connect to us, and opens the pubsub stream very fast, preloaded with the list of topic its subscribed to
2 - We see that we have a topic in common, so we GRAFT him
3 - "sendConn" stream is setup.
Most of the time, 3 happens before 2. But when 2 happens first, the GRAFT is simply swallowed by this:
https://github.com/status-im/nim-libp2p/blob/1711c204eab2596e4bd42b162d630bc262704daf/libp2p/protocols/pubsub/pubsubpeer.nim#L253
and we end up with an assymetric mesh.
This PR simply wait for …
> Fix PubSub subscribe on connection race condition

- libp2p/connmanager.nim
- tests/testconnmngr.nim
This system allows you to wait for a connection from a specific peer. It will bypass the `maxConnectionsPerPeer`, since you know you are waiting for him (but not the global limit of connections)
This is useful for AutoNat, HolePunching, maybe others
Also.. turns out the maxConnectionsPerPeer was off by one (hurray). I fixed it here, but maybe we should leave it as is to avoid changing the behavior. idk
EDIT: reverted, breaks to many things
> Add expected connections to connmngr

- libp2p/connmanager.nim
- libp2p/protocols/connectivity/autonat/client.nim
- libp2p/protocols/connectivity/autonat/server.nim
- libp2p/protocols/connectivity/autonat/service.nim
- tests/testautonatservice.nim
- tests/testconnmngr.nim
Uses https://github.com/status-im/nim-libp2p/pull/845 to avoid the maxConnectionsPerPeer limits, and pauses the service when we are close to the global limit.
The idea is that if you are close to the global limit, you had time to detect your current status. Changing the accept loop to always accept autonat would be tricky to do properly
> Autonat service: handle connections limits

- examples/circuitrelay.nim
- libp2p/dialer.nim
- libp2p/protocols/connectivity/relay/rtransport.nim
- libp2p/services/autorelayservice.nim
- libp2p/transports/tcptransport.nim
- libp2p/transports/tortransport.nim
- libp2p/transports/transport.nim
- libp2p/transports/wstransport.nim
- tests/commoninterop.nim
- tests/testautorelay.nim
- tests/testrelayv1.nim
- tests/testrelayv2.nim
In order to make the relay transport dial consistent with the others dial.
The PeerId might be useful for Quic and Webrtc aswell.
> Add the peerId to the transport.dial

- libp2p/transports/tcptransport.nim
#822 was breaking with old chronos versions
> Fix backward compatibility of #822

- .github/workflows/interop.yml
Waiting on https://github.com/libp2p/test-plans/pull/138
Will test a simple ping with every go & rust version, for every transport, muxer & encryption combo
> Interop tests

- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/gossipsub/scoring.nim
When two peers graft themselves at the same time, they both process the graft coming from the other peer.
If, while processing this graft, they decide to prune him for some reason, they will prune him without removing him from the local mesh.
This commit instead ignore grafts from peers already in mesh.
When pruning while processing a graft, we send a backoff but don't store it. Not anymore
I don't see any reason not to give point to a peer outside of the mesh for being first to deliver.
> Various gossipsub fixes

- libp2p/connmanager.nim
- libp2p/muxers/mplex/mplex.nim
- libp2p/muxers/muxer.nim
- libp2p/muxers/yamux/yamux.nim
- tests/helpers.nim
- tests/testconnmngr.nim
- tests/testmplex.nim
- tests/testyamux.nim
* Add getter function to access the connections and streams within each connection.
* This would allow nim-libp2p users to have a better view on the connections/streams they have, giving access to its direction, protocol being used and other relevant fields.
Closes https://github.com/status-im/nim-libp2p/issues/866
> Add getters for conns and streams

- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/peertable.nim
Thanks @alrevuelta for the report
dOut wasn't actually looking at the current number of outgoing peers, it just grafted up to dOut everytime
> Fix gossipsub dOut handling

- libp2p/protocols/connectivity/autonat/service.nim
- libp2p/services/autorelayservice.nim
- libp2p/services/hpservice.nim
- tests/testautonatservice.nim
The motivation is to make it cheaper to always run the Hole Punching Service
* Execute callHandler only if there was a change in reachability or confidence
* Setup autorelay service only if it isn't running and stop it only if it is running
> Autonat and HP changes

- libp2p/protocols/pubsub/pubsubpeer.nim
Currently, if we can't establish a sendConn, we will swallow messages, which can lead to asymmetric mesh and useless memory usage
This PR changes the behavior to consider the peer disconnected if we can't establish a sendConn in 5 seconds
> GossipSub: remove peer if we can't establish sendConn

- libp2p/switch.nim
- libp2p/transports/tcptransport.nim
- libp2p/transports/wstransport.nim
Ref https://github.com/status-im/nimbus-eth2/issues/5004
Updated according to @cheatfate: `TransportTooManyError` & `TransportAbortedError`: log & continue instantly, everything else: crash the loop
> Transports: handle TransportAbortedError properly

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/gossipsub/types.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/messages.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
The gossipsub ping will be used for various things as part of the https://github.com/status-im/nim-libp2p/issues/850
Introducing it today will enable us to test said optimizations on real networks to make sure they are viable
It is capped to make sure it doesn't introduce any security issues
> Add GossipSub ping

- libp2p/crypto/crypto.nim
Assigning to fields of `var` case objects emits `ProveField` warnings. We disable them in `make` based builds but they may pop up when building manually with `nim c`. Suppress them for the `init` function. Note that suppressing doesn't work on generics, so need to wrap with `template`.
> avoid `ProveField` warning in `crypto.init`

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/scoring.nim
When a score is restored from the in-memory peer stats, we should check it instantly and kick the peer if it's below the threshold.
> Gossipsub scoring improvements

- libp2p/transports/wstransport.nim
We found that a 'TransportOsError' can be raised by the next:
https://github.com/status-im/nim-libp2p/blob/224f92e17251464984d6906316c54d2e1108ae43/libp2p/transports/wstransport.nim#L260
let req = await finished
Then, that 'TransportOsError' exception was re-raised in `wstransport` and caught by the `switch.accept` proc, which made the main accept loop end accepting new upcoming connections because 'TransportOsError' is 'CatchableError'.
https://github.com/status-im/nim-libp2p/blob/224f92e17251464984d6906316c54d2e1108ae43/libp2p/switch.nim#L277
https://github.com/status-im/nim-libp2p/issues/927
> wstransport.nim: avoid re-raising 'TransportOsError' to avoid stopping `switch.accept`

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/messages.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
- tests/pubsub/testgossipsub.nim
Implements https://github.com/libp2p/specs/pull/548
> GossipSub: IDontWant

- libp2p/transports/wstransport.nim
https://github.com/status-im/nim-websock/pull/148 Broke backward compatibility
This patch is compatible with both the current & new version
> nim-websock new version compatibility

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/types.nim
- tests/pubsub/testgossipsub.nim
This is to replace the hard-coded value in https://github.com/status-im/nim-libp2p/pull/911
> Bandwidth estimate as a parameter

- libp2p/crypto/crypto.nim
- libp2p/crypto/ecnist.nim
`secio` can get its helpers directly from the `ecnist` module - but that doesn't really matter because it's also deprecated
this (significantly) reduces libp2p dependencies on bearssl speeding up compile times when not used
> avoid importing `ecnist` when not needed

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/gossipsub/types.nim
- tests/pubsub/testgossipsub2.nim
Currently, only the published messages are relayed to direct peers
However the spec states that all valid messages should be
Also, forceDial the direct peers to dial them even if we are full
> GS: Relay messages to direct peers

- libp2p/builders.nim
- libp2p/upgrademngrs/muxedupgrade.nim
- libp2p/upgrademngrs/upgrade.nim
- tests/testnoise.nim
This is no longer necessary since #807
> Remove ConnManager from Upgrade

- libp2p/transports/wstransport.nim
Should fix https://github.com/waku-org/nwaku/issues/2140
> Fix WS transport when the connection aborts

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/scoring.nim
- tests/pubsub/testgossipsub.nim
- "e2e - GossipSub should not rate limit decodable messages below the size allowed" test was flaky because sometimes the test would behave differently from what was expected due to failed signature verification. Always disabling the signature hopefully will fix it. 
- Another test was added for the case when the rate limit happens due to invalid domain messages.
> Rate limit fixes

- libp2p/errors.nim
- libp2p/transports/tcptransport.nim
This helps keep libp2p compatible with both chronos v3 and v4 while v4 is being developed (in particular https://github.com/status-im/nim-chronos/pull/470)
> fix chronos v4 compat

- libp2p/protocols/connectivity/dcutr/client.nim
- libp2p/protocols/connectivity/dcutr/server.nim
- tests/testdcutr.nim
- tests/testhpservice.nim
Make the code comply with the spec - on a TCP Simultaneous Connect, for the purpose of all protocols run on top of this TCP connection, the dcutr server is assumed to be the TCP client (Out connection), and the dcutr client the TCP server (In connection). More on https://github.com/libp2p/specs/blob/master/relay/DCUtR.md#the-protocol
> fix(dcutr): make the dcutr client inbound and the server outbound

- libp2p/multiaddress.nim
- libp2p/multicodec.nim
- tests/testmultiaddress.nim
The initial implementation of QUIC in go-libp2p was based on draft-ietf-quic-transport-29 (or simply, draft-29). At the time, draft-29 was implemented because RFC 9000 was yet to be finalized. Eventually go-libp2p added support for RFC 9000 in addition to draft-29, supporting two QUIC versions. However, the multiaddresses for these versions used the same format and thus were indistinguishable in the past.
By using different code points, quic-v1 for RFC 9000 and quic for draft-29, libp2p can now distinguish between the two versions.
The multiaddress for a QUIC listener accepting RFC 9000 connections looks like this: /ip4/192.0.2.0/udp/65432/quic-v1/, whereas the for the draft version, the multiaddress would be /ip4/192.0.2.0/udp/65432/quic/.
Nodes that support multiple versions can offer …
> fix(multiaddress): add quic-v1 multiaddress support

- libp2p/protocols/connectivity/dcutr/core.nim
- tests/testdcutr.nim
Accepts addresses like /ip4/198.51.100/tcp/1234/p2p/QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N as a dialable tcp address
> fix(dcutr): handle tcp/p2p addresses

- libp2p/builders.nim
- libp2p/muxers/yamux/yamux.nim
- libp2p/protocols/connectivity/relay/rconn.nim
- tests/testrelayv2.nim
Trying to use the circuit relay v2 with Yamux raises some issues:
- The direction of the RelayConnection wasn't rightly set creating an error. To go deeper, this is a description of what happened:
- A connects to Relay (A direction is outbound and Relay direction is inbound)
- A reserves a slot on Relay
- B connects to Relay (B direction is outbound and Relay direction is inbound)
- B connects to A through the Relay (A and B direction were both outbound, [which is wrong](https://github.com/hashicorp/yamux/blob/master/spec.md?plain=1#L64-L67), causing an error to be raised).
- As we didn't make the YamuxChannel inherit from BufferStream, we had to manage the isEof which was not implemented. The main reason as to why we didn't use BufferStream is because the way it works would have made the …
> fix(yamux): doesn't work in a Relayv2 connection

- libp2p/protocols/identify.nim
Currently, we use the ObservedAddrManager only to find our dialable external NAT address. Therefore, addresses like "...\p2p-circuit\p2p\..." and "\p2p\..." are not useful to us.
> fix(identify): do not add p2p and relayed addrs to observed addr manager

- libp2p/dial.nim
- libp2p/dialer.nim
- libp2p/protocols/connectivity/dcutr/client.nim
- libp2p/protocols/connectivity/dcutr/server.nim
- libp2p/protocols/secure/secure.nim
- libp2p/switch.nim
- libp2p/transports/transport.nim
- libp2p/upgrademngrs/muxedupgrade.nim
- libp2p/upgrademngrs/upgrade.nim
- tests/stubs/switchstub.nim
- tests/testdcutr.nim
- tests/testhpservice.nim
- tests/testnoise.nim
During DCUtR, the listener initiates the direct connection (it is called the DCUtR client) attempt and must connect to the other peer as the incoming upgrade direction. Yamux must use this direction to decide on using odd or even stream IDs, not the underlying connection direction. It means we need to change the underlying TCP connection direction to Inbound, despite it being a dial.
This is an unusual case where a peer initiates a connection, but should treat it as incoming. The reason is probably that DCUtR happens when the other remote peer dials a peer's relayed address, therefore the original connection was in fact incoming.
Related:
https://github.com/libp2p/specs/tree/master/yamux
https://github.com/libp2p/specs/blob/master/relay/DCUtR.md
> fix(dcutr): update the DCUtR initiator transport direction to Inbound

- .github/workflows/multi_nim_common.yml
- .github/workflows/multi_nim_devel.yml
- .github/workflows/multi_nim_legacy.yml
We have "unstable" as a default branch. Others may expect from it more stability than its name suggest. I propose to make "Daily" workflow more reliable by moving tests with Nim Devel to separate (experimental?) workflow.
> fix: move workflows for Nim Devel and legacy i386 from "Daily"

- .github/workflows/multi_nim_common.yml
matrix-prep job has been in multi_nim_common.yml without any additional definitions. Dependent workflows cannot run.
Remove useless job matrix-prep
> fix: remove forgotten "matrix-prep" job

- libp2p/protocols/identify.nim
It is difficult to associate the identify message with a connection from other log messages. Attaching the information about the corresponding `Connection` object to identify message logs makes this easier.
> include connection info when logging identify message

- libp2p/multiaddress.nim
Simple PR to avoid using the deprecated type `ValidIpAddress`, in favour of `IpAddress`.
> libp2p/multiaddress.nim: use of IpAddress instead of ValidIpAddress

- libp2p/muxers/yamux/yamux.nim
- tests/testyamux.nim
There was a clear lack of comments on Yamux. This PR should solve this problem.
> docs: add comments and improve yamux readability

- libp2p/muxers/yamux/yamux.nim
Simulating yamux with a few hundred nodes showed some compilation issues with the way the metrics were implemented.
- Buckets are now ordered (which was causing a compilation error).
- `write` now updates `libp2p_yamux_send_queue` and not `libp2p_yamux_recv_queue`
> fix: yamux metrics

- libp2p/errors.nim
- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- tests/pubsub/testgossipinternal.nim
- tests/pubsub/testgossipsub.nim
**Motivation:** We are assuming the local peer might be spending too much time/bandwidth relaying messages rather than publishing its own messages, which could increase latency for the latter.
**Objective:** To enhance efficiency in message processing by prioritizing immediate dispatch of peer-published messages, and managing other messages through a queuing system.
**Changes:**
**Immediate Dispatch for Peer-Published Messages:** Ensures top priority by immediately sending messages published by the peer.
**Queued Handling for IWANT Replies and Relay Messages:** Introduces a unified queuing system for both replies to "IWANT" messages and messages from other peers that need relaying. These are processed after peer-published messages.
**Asynchronous Task Queue Tracking:** Implements an …
> feat: message prioritization with immediate peer-published dispatch and queuing for other msgs

- libp2p/builders.nim
- libp2p/muxers/yamux/yamux.nim
- tests/testyamux.nim
This PR adds a timeout to Yamux so that it works in the same way as Mplex. Adds a couple of tests.
Fixes a bug revealed by tests where `result.reset()` called `Future[void].reset()` instead of `YamuxStream.reset()`
> feat: Yamux timeout

- tests/testheartbeat.nim
The `simple heartbeat` test is flaky:
```
================
/home/runner/work/nim-libp2p/nim-libp2p/tests/testnative 'Heartbeat::simple heartbeat'
----------------
/home/runner/work/nim-libp2p/nim-libp2p/tests/testheartbeat.nim(31, 10): Check failed: i in 9 .. 11
i was 12
9 .. 11 was 9 .. 11
[FAILED ] (  0.33s) simple heartbeat
```
Increase its timing tolerances to reduce the likelihood of this happening under load.
> increase tolerance of `simple heartbeat` test

- libp2p/cid.nim
The `MultiBase.encode(..., Cid)` function is unused and can be removed. If it were used, it would need a `{.raises: [LPError].}` annotation to successfully compiled. As it lacks it, there cannot be external callers.
> remove unused `MultiBase.encode(..., Cid)` function

- libp2p/errors.nim
- libp2p/protocols/secure/secure.nim
- libp2p/stream/lpstream.nim
- libp2p/transports/tcptransport.nim
- tests/errorhelpers.nim
- tests/helpers.nim
- tests/hole-punching-interop/hole_punching.nim
We use a generically seeming helper to help us track three `Future` exceptions throughout the entire codebase. Move the helper to tests where it finds more use. The helper has several design flaws that make it incompatible with `{.async: (raises).}` usage, and has the potential to swallow one of the three exceptions that we track with it.
The semantics should not change in this PR, this is a pure refactoring.
> move `allFutureThrowing` helper to tests

- libp2p/stream/lpstream.nim
- libp2p/transports/tcptransport.nim
- tests/helpers.nim
- tests/testbufferstream.nim
The previous `addTracker` / `getTracker` Chronos APIs were deprecated. Switch to their equivalent new APIs which need less manual management.
> use new Chronos `trackCounter` APIs for leaks checks in tests

- libp2p/stream/lpstream.nim
There are a handful of `LPStreamError` types that are fully unused. They can be removed.
> remove unused `LPStreamError` types

- libp2p/protocols/secure/noise.nim
- libp2p/protocols/secure/secio.nim
When higher modules read from streams, they often use `Noise` / `Secio` interchangeably with other streams. It simplifies exception handling a lot if they reflect their nature as specialized stream wrappers by also inheriting from `LPStreamError` instead of the root `LPError`.
> change `SecioError` and `NoiseError` to descendants of `LPStreamError`

- libp2p/muxers/yamux/yamux.nim
The `Msg Rcv` trace log does not sanitize the buffer against binary data, which may trigger oddities in the terminal displaying it, as binary control characters get interpreted. Using `shortLog` instead is consistent with `Mplex` and displays the start and end as hex. It makes more sense anyway because the exchanged messages actually do contain binary headers very often, and displaying these as string is most likely incorrect.
> do not log yamux buffers without sanitization (trace log level)

- libp2p/muxers/yamux/yamux.nim
When there is an error during the final graceful `{Fin}`, we currently don't call `channel.actuallyClose()`. Fix that by ignoring such errors.
> don't forget closing the stream when final `{Fin}` fails in yamux

- libp2p/muxers/yamux/yamux.nim
- libp2p/protocols/connectivity/relay/utils.nim
- libp2p/protocols/secure/secure.nim
- libp2p/transports/tcptransport.nim
`or` futures are currently bugged when using `cancelAndWait` on them. This sometimes show when tests run several minutes longer until the mess is unstucked through a timeout that pokes the machinery again. Use `race` to avoid the lockup.
- https://github.com/status-im/nim-chronos/issues/516
> use `race` instead of `or` to avoid lockup

- libp2p/muxers/yamux/yamux.nim
When a yamux channel is reset, the connection may still be in use with pending writes. In that situation, the socket cannot be used to send the terminating `{Rst}` packet without corrupting the data. Waiting for the pending write to complete is also not too useful, and also would need a refactoring to even support so, as we don't track the `trySend` future that is currently writing, and also already purged the `sendQueue`.
Note that this also fixes assertions depending on chronos scheduling in local tests that use `pushData` on `BufferStream`. Because `pushData` checks no other pushes are in progress, tests may have randomly failed.
> in yamux, do not write `{Rst}` packet to stream that's in use

- libp2p/muxers/yamux/yamux.nim
There are two edge cases that currently trigger `KeyError`:
1. `await newStream.open()` succeeds, but Chronos injects an implicit suspend point when an `{.async.}` function that suspended returns. During this implicit suspend point, another task could get scheduled and close the stream, which removes it from `m.channels` again. `let channel = m.channels[header.streamId` then gives `KeyError`. More explanation of implicit suspend point on return after await: https://github.com/status-im/nim-chronos/pull/273
2. During the `Flush the data` block, `await m.connection.readExactly` is called which may suspend. If it suspends, same as above, another task may get scheduled that closes the stream, also resulting in the `KeyError` below.
The `YamuxError` is subsequently properly handled below.
> avoid `KeyError` in edge case of yamux handler

- libp2p/transports/wstransport.nim
Ensure all errors raised by `nim-websock` are caught. That library is not yet updated regarding `{.async: (raises).}`, so an extra entry is needed for `CatchableError` to avoid polluting the callstack with it.
> catch `WebSocketError` in `wstransport`

- libp2p/muxers/yamux/yamux.nim
All errors raised by `nim-libp2p` should descend from `LPError`. `YamuxError` was not correctly classified. Proposing it to be a specialized `MuxerError`, in line with `mplex` and `muxer` errors.
> define proper parent error type for `YamuxError`

- libp2p/muxers/mplex/lpchannel.nim
To avoid others stumbling across this one, document a known crash when running `nimble test` on macOS with Nim 2.0.2.
> document known `--mm:orc` crash

- libp2p/builders.nim
`newStandardSwitch` has an `addrs` param that defaults to a constant if not specified. The constant should always parse fine, so `expect` it as such, instead of having unpredictable exception behaviour.
> default `MultiAddress` param for `newStandardSwitch` does not raise

- libp2p/protocols/connectivity/relay/utils.nim
Annotate `relay/utils` module with `{.async: (raises).}`. These build on top of `writeLp` and can be updated independently of the rest of libp2p.
> `{.async: (raises).}` for `relay/utils.nim`

- libp2p/multistream.nim
- libp2p/protocols/connectivity/relay/relay.nim
- libp2p/protocols/protocol.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/rendezvous.nim
Annotate `MultistreamSelect` with `{.async: (raises).}` and ensure that `handle` returns a `MultiStreamError` instead of `CatchableError` in the "invalid first message" case.
> `{.async: (raises).}` for `MultistreamSelect`

- libp2p/dialer.nim
There may be an error during the connection transport upgrade (evolving from raw transport to a multiplexed stream.)
Simple simple change only makes it more explicit that the error refers to the connection upgrade and not to the app upgrade.
We've noticed this confusion in a user after upgrading the `nwaku` version.
> libp2p/dialer.nim: tiny log change to make it clearer a connection upgrade

- libp2p/protocols/pubsub/pubsubpeer.nim
otherwise, the use of `asyncSpawn` results in breakage
> avoid cancelling send future

- libp2p/muxers/yamux/yamux.nim
In original location, `header.length > 0` check was inside the `header.msgType == Data` check. During #1045, it was accidentally moved outside and applied to all the `header.msgType`. Move back.
> move `header.length` check in `yamux` to original location

- libp2p/multistream.nim
- libp2p/transports/transport.nim
- libp2p/upgrademngrs/muxedupgrade.nim
- libp2p/upgrademngrs/upgrade.nim
The next layer of modules that can get `{.async: (raises).}` annotations are the `upgrademngrs`. This is the first layer that mixes so many error types that it makes sense to start with `{.async: (raises: [LPError]).}` especially because the callers add raw `LPError` as well. It may be worthwhile to try and wrap inner exceptions in a proper outer type, but as this pattern spans large parts of the library, such wrapping should be investigated separately from initial annotation work.
> annotate `upgrademngrs` with `{.async: (raises).}`

- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/gossipsub/scoring.nim
- libp2p/protocols/pubsub/mcache.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/message.nim
- libp2p/protocols/pubsub/rpc/messages.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
- tests/pubsub/testgossipinternal.nim
- tests/pubsub/testgossipsub.nim
- tests/pubsub/testmcache.nim
- tests/pubsub/testmessage.nim
- tests/pubsub/utils.nim
Rename RPC's Message `topicIds` to `topicId`.
Please, do look carefully into this one as I'm not sure how a well covered by tests is the repo, and my changes could be breaking stuff.
Closes (hopefully): https://github.com/status-im/nim-libp2p/issues/1052
> fix(issue-1052): Single topic for RPC Message

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/types.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
This PR adds a default limit to the number of elements in the non-priority queue. When this limit has been reached, the peer will be disconnected. This limit can also be configured through a new GossipSub param `maxNumElementsInNonPriorityQueue`.
> feat: add max number of elements to non-prio queue

- libp2p/protocols/pubsub/gossipsub.nim
Before this PR, there were two ways of creating a GossipSubParam instance: using `GossipSubParam.init`or the `GossipSubParams(propertyName: propertyValue)` pattern. In the first case, there was no way to specify only a few values and use the rest as the default defined by nim-libp2p, as the `init` proc doesn't accept params. It was the same for the second case, the values not specified would be initialized as the nim default value for their types. This PR creates a new constructor with default values defined for all the params. The user can choose which ones to override or use the default value defined by the library.
> improvement: create a new gossipsub constructor

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/types.nim
I believe `explicit` is used to check if the `GossipSubParams` instance was created by the user either passing params  to `GossipSubParams(...)` or `GossipSubParams.init(...)`. In the first case `explicit` should be set to `true` when calling the `Nim` constructor, in the second case, the param isn't necessary and should be always be set to true by `init`. If none of those options were used, it means the instance was created by using Nim default values. In this case, `GossipSubParams.init()` should be called to set the values to their default value defined by nim-libp2p.
https://github.com/status-im/nim-libp2p/blob/5e55ca3b69e18a56a0a5a34941676f4df08523ae/libp2p/protocols/pubsub/gossipsub.nim#L774
> fix: remove explicit param from GossipSubParams constructor

- libp2p/transports/tcptransport.nim
Changes:
- Reset `acceptFuts` seq when `stop` is invoked: this is needed to properly perform connection restarts between nodes and this issue was detected in `nwaku` tests, as explained in https://github.com/waku-org/nwaku/issues/2145
- Add a debug log when an exception is caught. This change is not directly needed by the "reconnect" issue mentioned in the previous point.
> fix: reset accept fut in stop

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
Salting `idontwant` ensures the message id does not exceed reasonable length and prevents the hash table itself from being attacked while at the same time bounding memory consumption.
> salt `idontwant`

- libp2p/protocols/pubsub/pubsubpeer.nim
Fix for:
`crash on Nimbus 24.4.0 in production 9:03 EDT. 09:03:24.578950-04:00 localhost nimbus-beacon[4803]: Error: unhandled exception: Asynchronous task [sendMsgSlow() at pubsubpeer.nim:301] was cancelled! [FutureDefect]`
Using `await` on a shared `Future` can raise an unexpected `CancelledError` if this `Future` gets canceled indirectly by another task. `race` (and `join` in newer versions of chronos) creates a separate future that "insulates" the shared future from the cancellation flow. See https://github.com/status-im/nim-chronos/commit/8166d7d0f16119ad74184dd3ccc001f3035537b7#diff-a6bc56e6ac55acab484b1a94671287d6f72bc6311b3ea43482b438b517ec9390R172.
> fix: Asynchronous task [sendMsgSlow()] was cancelled [FutureDefect]

- libp2p/switch.nim
- tests/hole-punching-interop/hole_punching.nim
- tests/testautonatservice.nim
- tests/testautorelay.nim
- Setup services before peerinfo is updated - this allows services to set address mappers.
- Fix HP interop tests - improve condition related to relay addr being published.
- Disable wildcard resolver in `testautonatservice` and test `testautorelay`.
> fix(services): setup services before peerinfo is updated

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/gossipsub/types.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/utility.nim
- tests/pubsub/testgossipsub.nim
- tests/pubsub/utils.nim
- Support GossipSub 1.2 in the code
- Add utility template `template exclIfIt*[T](set: var HashSet[T], condition: untyped)`
- Renaming
closes https://github.com/vacp2p/nim-libp2p/issues/1102
> feat(gossipsub): support version 1.2.0

- libp2p/services/autorelayservice.nim
- tests/testautorelay.nim
Fix `testautorelay` due to wildcard resolver and improve its readability.
Related to https://github.com/vacp2p/nim-libp2p/pull/1099
> fix(tests): testautorelay

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsub.nim
- tests/pubsub/testgossipsub.nim
- tests/pubsub/utils.nim
closes https://github.com/vacp2p/nim-libp2p/issues/1115
> fix(gossipsub): pubsubpeer is created with wrong gossipsub version

- libp2p/muxers/yamux/yamux.nim
We used closedRemotely as a asynchronous flag which is not really the goal of a Future. For this specific case, an AsyncEvent makes more sense.
> chore(yamux): change closedRemotely from Future into AsyncEvent

- libp2p/protocols/pubsub/timedcache.nim
- tests/pubsub/testtimedcache.nim
This PR adds an optional `maxSize` to `TimedCache`. In this way, we can avoid the cache growing unbounded.
> feat: add maxSize to TimedCache

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .github/workflows/doc.yml
- .github/workflows/interop.yml
The `unstable` branch wasn't removed from some workflows and `interop` wasn't running on `master`.
> fix: run workflows on master

- .github/workflows/ci.yml
- libp2p.nimble
- tests/commontransport.nim
- tests/config.nims
This PR enables Nim 2.0.x with `refc` garbage collector on CI.
The following compilation error had to be fixed:  Error: undeclared identifier: 'acceptHandler`gensym435'; if declared in a template, this identifier may be inconsistently marked inject or gensym
> chore: enable Nim 2.0.x and fix compilation issues

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .github/workflows/daily_common.yml
- .github/workflows/doc.yml
The main motivation was to update the Ubuntu version on the daily job as it seemed it wasn't supported anymore.
macOS 14 fails immediately with no error msg, so we are using 13 for now.
> chore: update os images on ci

- libp2p/dialer.nim
We are trying to reduce the logs load in our fleets, and one of the most recurrent one is
```
Dialing canceled                           topics="libp2p dialer" tid=1 file=dialer.nim:67 err="Future operation cancelled!" peerId=16U*XAFJX3
```
which is quite spammy and doesn't give much info. 
In addition to that, its corresponding `Dialing address` log is in trace.
So adjusting the log level of `Dialing canceled` to trace :)
> chore: setting dialing canceled log to trace

- .github/workflows/ci.yml
The failure is due to incompatibility (in caching) after Nimble's v.0.14.0 update, where they changed the dependencies directory name from `pkgs` to `pkgs2`.
This PR includes the nim branch in the cache key to avoid the directory name issue. 
In the future, if we deprecate support for Nim 1.6 we may remove this.
fixes https://github.com/vacp2p/nim-libp2p/issues/1157
> fix(ci): windows-amd64 (Nim version-1-6)

- .github/workflows/ci.yml
- .pinned
- libp2p.nimble
- libp2p/crypto/curve25519.nim
- libp2p/crypto/ecnist.nim
- Add ubuntu-24-gcc-14 target on CI.  https://github.com/vacp2p/nim-libp2p/issues/1156 prevents us from using only Ubuntu 24.
- Made the changes necessary to support gcc 14. More info on https://github.com/status-im/nim-bearssl/pull/62
Fixes https://github.com/vacp2p/nim-libp2p/issues/1150
> fix: add gcc 14 support

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- tests/pubsub/testgossipsub.nim
Adding an `onValidated` observer which will run every time a message is received and validated. This comes from the necessity of precisely track message deliveries and network activity.
`onRecv` observers run before any check is performed on the received message, which means that it runs every time a duplicate or invalid message arrives, which is inefficient and inaccurate for our purpose of tracking only received, unique and valid messages. Therefore, adding this extra option of running an observer for every message after all validation checks pass.
> feat: adding onValidated observer

- libp2p/muxers/yamux/yamux.nim
At first glance, this fixes https://github.com/vacp2p/nim-libp2p/issues/1165.
It raises another issue: I always thought that Future unfinished caught in the GC were cancelled. But that doesn't always seem to be the case.
> fix(yamux): future leak

- libp2p/transports/wstransport.nim
For example:
```
/Users/runner/work/nim-libp2p/nim-libp2p/nimbledeps/pkgs2/websock-0.1.0-94f836ae589056b2deb04bdfdcd614fff80adaf5/websock/http/client.nim(173, 5) template/generic instantiation of `async` from here
/Users/runner/work/nim-libp2p/nim-libp2p/nimbledeps/pkgs2/websock-0.1.0-94f836ae589056b2deb04bdfdcd614fff80adaf5/websock/http/client.nim(165, 1) Warning: The raises pragma doesn't work on async procedures - use `async: (raises: [...]) instead. [User]
/Users/runner/work/nim-libp2p/nim-libp2p/nimbledeps/pkgs2/websock-0.1.0-94f836ae589056b2deb04bdfdcd614fff80adaf5/websock/websock.nim(257, 5) template/generic instantiation of `async` from here
/Users/runner/work/nim-libp2p/nim-libp2p/nimbledeps/pkgs2/websock-0.1.0-94f836ae589056b2deb04bdfdcd614fff80adaf5/websock/websock.nim(251, 1) …
```
> fix(transport): libp2p compilation in Nim version-2-0

- .github/workflows/daily_common.yml
- .github/workflows/daily_sat.yml
Use only on a daily job so we test out if it behaves correctly.
closes: https://github.com/vacp2p/nim-libp2p/issues/1174
> ci: Enable conditional SAT solving

- .github/workflows/linters.yml
Rollbacks to the previous `nph` command that shows what files aren't formatted.
> chore(CI): rollback nph change

- libp2p/transports/tcptransport.nim
Address the comments in https://github.com/vacp2p/nim-libp2p/pull/1164
> fix(transport): tcp accept fixes

- libp2p/connmanager.nim
Bring a bit more detail when the "Too many connections for peer" message is being logged. Particularly, we are adding the offending `peerId` and the stream direction
> chore(connmanager): also show peerID and dir when too many conns

- config.nims
- libp2p.nimble
- tests/config.nims
- Moving the `mm:refc` configuration to the main `config.nims` file makes it be used in tests and tasks that build examples.
- It's not clear why `skipParentCfg`was being used and it doesn't seem to be necessary.
> chore: move mm:refc config and remove skipParentCfg 

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/interop.yml
- .github/workflows/linters.yml
This change is necessary before enabling merge queues.  The `merge_group` event is needed to trigger the GitHub Actions workflow when a pull request is added to a merge queue.
The merge queue provides the same benefits as the Require branches to be up to date before merging branch protection but does not require a pull request author to update their pull request branch and wait for status checks to finish before trying to merge. More info on https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue.
> chore: add support to merge queues

- libp2p.nimble
Updating libp2p.nimble to 1.6.0.
This commit is planned to be tagged with 1.6.0.
The only new feature in this version is the highly experimental Quick transport. Still, it is a feature and justifies a minor version upgrade.
It also contains a few fixes and improvements (see commit history).
> chore(version): update libp2p.nimble to 1.6.0

- libp2p/discovery/rendezvousinterface.nim
- libp2p/protocols/rendezvous.nim
- tests/testrendezvous.nim
Hello!
This PR aim to refactor rendezvous code so that it is easier to impl. Waku rdv strategy. The hardcoded min and max TTL were out of range with what we needed and specifying which peers to interact with is also needed since Waku deals with peers on multiple separate shards.
I tried to keep the changes to a minimum, specifically I did not change the name of any public procs which result in less than descriptive names in some cases. I also wanted to return results instead of raising exceptions but didn't. Would it be acceptable to do so?
Please advise on best practices, thank you.
> feat: rendezvous refactor

- .github/workflows/interop.yml
- Adds our S3 bucket for caching docker images as Protocol Labs shut down their shared one.
- Remove the free disk space workaround that prevented the jobs from failing for using too much space for the images.
> chore(ci): Enable S3 caching for interop

- .github/workflows/interop.yml
Readd the free disk space job, as space issues still happen when building images.
> fix(CI): free disk space on interop transport job

- tests/pubsub/testgossipinternal.nim
Add documentation as requested.
> docs(test): handle IHAVE / IWANT tests

- .github/actions/install_nim/action.yml
- .github/workflows/ci.yml
- .github/workflows/daily_amd64.yml
- .github/workflows/daily_common.yml
- .github/workflows/daily_devel.yml
- .github/workflows/daily_i386.yml
- .github/workflows/daily_sat.yml
- .pinned
Broken due to an update to Nimble 0.16.2 for the version-2-0 branch. This PR sets the ref to the previous commit. Also, updates the key naming so it fits better.
Nim's commit list: https://github.com/nim-lang/Nim/commits/version-2-0/
In this PR some required job's names were changed. They need to be updated at repo-level so this PR can be merged.
> fix(ci): nim 2.0 dependency failure

- libp2p/nameresolving/dnsresolver.nim
- libp2p/nameresolving/mockresolver.nim
- libp2p/nameresolving/nameresolver.nim
Modernize `nameresolving` modules to track `{.async: (raises).}`.
> feat(nameresolving): Add `{.async: (raises).}` annotations

- .github/actions/install_nim/action.yml
- .github/workflows/ci.yml
- .github/workflows/daily_common.yml
- examples/go-daemon/daemonapi.md
This PR adds the macOS 14 GitHub runner that uses the arm64 cpu.
> chore(ci): add arm64 for macOS

- examples/tutorial_4_gossipsub.nim
- examples/tutorial_6_game.nim
- libp2p/daemon/daemonapi.nim
- libp2p/protobuf/minprotobuf.nim
- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/protocols/pubsub/gossipsub/scoring.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/rpc/protobuf.nim
- tests/commoninterop.nim
- tests/pubsub/testfloodsub.nim
- tests/pubsub/testgossipinternal.nim
- tests/pubsub/testgossipsub.nim
- tests/pubsub/testgossipsub2.nim
- tests/pubsub/utils.nim
- tests/testdaemon.nim
- tests/testminprotobuf.nim
This PR adds `{.async: (raises).}` annotations to the pubsub package.
The cases in which a `raises:[CatchableError]` was added were due to not being part of the package and should probably be changed in a separate PR
> feat(pubsub): add `{.async: (raises).}` annotations

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/types.nim
- libp2p/utility.nim
- tests/pubsub/testgossipsub.nim
- tests/pubsub/utils.nim
Closes #1224 
The following changes were done:
1. Once a message is broadcasted, if it exceeds the threeshold to consider it a large message it will send an IDONTWANT message before publishing the message
https://github.com/vacp2p/nim-libp2p/blob/4f9c21f6999a58dff0fde2d4f031086bc846c9f7/libp2p/protocols/pubsub/gossipsub.nim#L800-L801
2. Extracts the logic to broadcast an IDONTWANT message and to verify the size of a message into separate functions
3. Adds a template to filter values of a hashset without modifying the original
> feat: idontwant on publish

- .github/workflows/dependencies.yml
The branch `nim-libp2p-auto-bump-unstable` was not getting autobumped because at one point of time in nim-libp2p `unstable` branch was renamed to `master` branch. Since the workflow file depended on `GITHUB_REF`, it was instead updating `nim-libp2p-auto-bump-master` instead of `nim-libp2p-auto-bump-unstable`
> fix: use target repository branch as suffix for `nim-libp2p-auto-bump-`

- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/rpc/message.nim
As commented on https://github.com/vacp2p/nim-libp2p/pull/1243#issuecomment-2639659840 the only scenario in which is it possible to have this exception being raised is due to a misconfig when initializing a message in 
- https://github.com/vacp2p/nim-libp2p/blob/master/libp2p/protocols/pubsub/floodsub.nim#L215-L219
- https://github.com/vacp2p/nim-libp2p/blob/master/libp2p/protocols/pubsub/gossipsub.nim#L784-L788
Since `Message.init` is used only in these places and it's not expected for a consumer of nim-libp2p to create a `Message` themselves, adding this assertion is safe as it will immediatly indicate that the message is being initialized incorrectly.
> refactor(pubsub): do not raise exceptions on publish

- .github/workflows/linters.yml
- examples/tutorial_4_gossipsub.nim
- examples/tutorial_6_game.nim
- libp2p/crypto/hkdf.nim
- libp2p/discovery/discoverymngr.nim
- libp2p/muxers/yamux/yamux.nim
- libp2p/protocols/connectivity/autonat/server.nim
- libp2p/protocols/connectivity/relay/relay.nim
- libp2p/protocols/protocol.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- libp2p/stream/bufferstream.nim
- libp2p/transports/tcptransport.nim
- libp2p/wire.nim
- tests/commoninterop.nim
- tests/testinterop.nim
- CI was failing because code style was not up to the `nph` guidelines. This PR just fixes code style to conform to `nph`.
- Updated `nph` version to 0.6.1
> style: fix code style with nph

- libp2p/daemon/daemonapi.nim
- libp2p/daemon/transpool.nim
- libp2p/utility.nim
- libp2p/wire.nim
- tests/commoninterop.nim
- tests/testdaemon.nim
`CatchableError` in this PR where listed because `P2PStreamCallback` had it listed before in https://github.com/vacp2p/nim-libp2p/pull/1233 effort.
part of https://github.com/vacp2p/nim-libp2p/issues/962 effort.
> chore: specify raising exceptions in `daemon` module

- libp2p/muxers/mplex/lpchannel.nim
- libp2p/muxers/yamux/yamux.nim
Add more debug logs. Interesting to analyse an issue discovered by @AlbertoSoutullo
> chore: add trace log to analyse remote stream reset

- libp2p/connmanager.nim
- libp2p/protocols/connectivity/autonat/client.nim
- libp2p/protocols/connectivity/autonat/server.nim
- libp2p/protocols/connectivity/autonat/service.nim
- libp2p/protocols/connectivity/dcutr/client.nim
- libp2p/protocols/connectivity/dcutr/core.nim
- libp2p/protocols/connectivity/relay/relay.nim
- libp2p/protocols/identify.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/rendezvous.nim
- libp2p/services/autorelayservice.nim
- libp2p/services/hpservice.nim
- tests/stubs/autonatclientstub.nim
- tests/testswitch.nim
this PR specifies raised exceptions in `protocols` module. it is part 2, continuation to  #1260.
part of https://github.com/vacp2p/nim-libp2p/issues/962 effort.
> chore(protocols):  specify raised exceptions (part 2)

- .github/workflows/ci.yml
- .pinned
- libp2p.nimble
- libp2p/transports/tls/certificate.nim
- tests/hole-punching-interop/Dockerfile
- tests/transport-interop/Dockerfile
- tests/transports/tls/testcertificate.nim
This PR implements the certificate generation and parsing for https://github.com/libp2p/specs/blob/master/tls/tls.md.
> feat(tls-certificate): generate and parse libp2p tls certificate

- examples/circuitrelay.nim
- examples/directchat.nim
- examples/helloworld.nim
- examples/tutorial_2_customproto.nim
- examples/tutorial_3_protobuf.nim
- examples/tutorial_5_discovery.nim
- examples/tutorial_6_game.nim
- libp2p/protocols/connectivity/autonat/server.nim
- libp2p/protocols/connectivity/dcutr/server.nim
- libp2p/protocols/connectivity/relay/client.nim
- libp2p/protocols/connectivity/relay/relay.nim
- libp2p/protocols/identify.nim
- libp2p/protocols/perf/server.nim
- libp2p/protocols/ping.nim
- libp2p/protocols/protocol.nim
- libp2p/protocols/pubsub/floodsub.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/rendezvous.nim
- libp2p/protocols/secure/plaintext.nim
- libp2p/protocols/secure/secure.nim
- tests/commoninterop.nim
- tests/testautonat.nim
- tests/testmultistream.nim
- tests/testnoise.nim
- tests/testping.nim
- tests/testrelayv1.nim
- tests/testrelayv2.nim
- tests/testswitch.nim
- tests/testtortransport.nim
initially `LPProtoHandler` has specified zero raised exceptions. this PR is adding `CancelledError` as only exception to the list.
part of https://github.com/vacp2p/nim-libp2p/issues/1270 effort.
> chore(protocol): handler to propagate CancelledError

- libp2p/transports/tls/certificate.nim
- tests/transports/tls/testcertificate.nim
- setting distinguishable issuer name for certificate. each peer id is like organization that issues self signed certificates for themself, so it makes sense to have peer id as CN. other implementations like [go-libp2p](https://github.com/vladopajic/go-libp2p/blob/tls-certificate-test-vector/p2p/security/tls/crypto.go#L284) are also setting unique issuer for each certificate (but generating random id seems unnecessary when we can use peer id).
- moved utilities from test since `certificate.nim` now imports `peerid.nim`
> feat(certificate): set distinguishable issuer name with peer id

- .pinned
- libp2p.nimble
- libp2p/transports/tls/certificate.c
- libp2p/transports/tls/certificate.h
- libp2p/transports/tls/certificate.nim
- libp2p/transports/tls/certificate_ffi.nim
- tests/testnative.nim
@vladopajic, @kaiserd 
I attempted to fix the compilation errors occuring in Linux i386 and macOS ARM64 (as seen in [this PR](https://github.com/vacp2p/nim-libp2p/pull/1278)), but I was not successful. There's an open issue related to [missing symbols in ARM64](https://github.com/Mbed-TLS/mbedtls/issues/9895) so it's probably the same problem affecting us. Something similar likely happens with Linux i386.
To prevent this from becoming a blocker, I quickly translated the certificate generation code to use OpenSSL instead of MbedTLS, (which I think might even make sense, given that we're already using OpenSSL via ngtcp2 + picoTLS), and Iwould suggest to use this instead of MbedTLS until the ARM64 compilation issues are resolved; and even consider to continue using OpenSSL until we can full …
> refactor: use openssl instead of mbedtls

- .pinned
- libp2p.nimble
- libp2p/builders.nim
- libp2p/dial.nim
- libp2p/discovery/discoverymngr.nim
- libp2p/muxers/muxer.nim
- libp2p/nameresolving/nameresolver.nim
- libp2p/protocols/secure/secure.nim
- libp2p/stream/connection.nim
- libp2p/stream/lpstream.nim
- libp2p/switch.nim
- libp2p/transports/quictransport.nim
- libp2p/transports/tortransport.nim
- libp2p/transports/transport.nim
- libp2p/upgrademngrs/upgrade.nim
- libp2p/wire.nim
- tests/commoninterop.nim
- tests/testinterop.nim
- tests/testquic.nim
- tests/testswitch.nim
- tests/transport-interop/main.nim
This PR enables quic transport with a proper TLS backend, and tests connection and comms between two nodes. 
Do note that one of the commits changes the `not implemented` assertion to something that gives a bit more context, so it's easier to know which abstract method a dev forgot to implement.
> feat: quic

- .pinned
- libp2p.nimble
- libp2p/transports/quictransport.nim
- libp2p/transports/tls/certificate.c
- tests/transport-interop/Dockerfile
While manually testing interop between diff implementations, i noticed that I forgot to set the peerId on incoming connections. This PR fixes that. Do notice that I had no easy way to obtain the peerId hence why I re-parse the certificate again.
Also, some impl did not understand the certificate usage, so I commented it in the meantime, and will fix it on subsequent PR tomorrow
Requires:
- https://github.com/vacp2p/nim-quic/pull/65
> fix: set peerId on incoming Quic connection

- libp2p/transports/tls/certificate.nim
we should use .cstring ideally only at the FFI boundary and not return them from procs unless we can be sure that it will outlive the proc lifetime
> fix: unsafe string usage

- libp2p/protocols/protocol.nim
removing deprecated utilities since previous release already introduced braking change, so keeping these is unnecessary.
> chore(protocols): remove deprecated utilities

- libp2p/builders.nim
- libp2p/multiaddress.nim
- libp2p/multicodec.nim
- libp2p/stream/bridgestream.nim
- libp2p/transports/memorymanager.nim
- libp2p/transports/memorytransport.nim
- tests/testbridgestream.nim
- tests/testdiscovery.nim
- tests/testmemorytransport.nim
- tests/testnative.nim
this pr add `memory` transports that can be used as drop in replacement for other transports in case if users don't need to go into network stack. memory transport only works in scope of same process.
> feat(transport): add memory transport

- libp2p/transports/quictransport.nim
- tests/testquic.nim
While reviewing code in more detail I saw that instead of having a `while true` and `continue` in the quic transport, we should instead return nil. This is gonna be later handled in here https://github.com/vacp2p/nim-libp2p/blob/master/libp2p/switch.nim#L273-L283 where we check whether the returned connection is nil or not. Since in this PR, when there's a QuicError, no connection will be returned, then we'll enter this condition https://github.com/vacp2p/nim-libp2p/blob/master/libp2p/switch.nim#L281-L283 . Do note that this code is already inside a `while transport.isRunning`. https://github.com/vacp2p/nim-libp2p/blob/master/libp2p/switch.nim#L264 so it will try to `accept` again in the next iteration
This should be refactored later in all transports to not return nil, but an option …
> fix: do not use while loop for quic transport errors

- libp2p/discovery/rendezvousinterface.nim
- libp2p/protocols/rendezvous.nim
- tests/testrendezvous.nim
Fixes (most of) #1307 
1. Uses `Opt[string]` for `namespace` fields on `Cookie` and `request` (which does `Discover`s). You can now do `rdv.request()` or `rdv.request(Opt.none(string))` to get all namespaces.
2. Functions that timeout now get `timeout` as a parameter instead of hardcoded values
3.  Add `MaximumMessageLen` (4MB) as a safe max read size for `readLp`, similar to [go-libp2p's implementation](https://github.com/libp2p/go-libp2p/blob/v0.41.1/core/network/network.go#L19C1-L23C39)
> chore: rendezvous improvements

- libp2p.nimble
Changes:
- flags: `libp2p_pubsub_sign`, `libp2p_pubsub_verify`, `pubsub_internal_testing` and `libp2p_pubsub_anonymize` don't seem to be used anymore - which means we can simplify `nimble` task `testpubsub`
> chore(test): remove unused flags and simplify testpubsub

- libp2p.nimble
- tests/testall.nim
Changes:
- combine all tests (beside `testfilter`) to limit compilations and further improve Unit Tests execution time
Note: order of the imports matter: `testnative, testdaemon, ./pubsub/testpubsub, testinterop`. When I tried to run `testpubsub` last, a lot of tests failed, probably due to: https://github.com/vacp2p/nim-libp2p/issues/1330.
> test: combine tests

- libp2p.nimble
- tests/testall.nim
Changes:
- include `pubsub/testgossipinternal` in `testall`
- simplify `testfilter`, keep 2 cases:
- all schemes supported
- no scheme supported
- delete `test_slim`
> test: include missing tests in testall

- examples/tutorial_4_gossipsub.nim
- libp2p.nim
- mkdocs.yml
Some links refer back to the old `status-im` org, most of which redirect to corrected new repos, but a few of them don't. Fixed the ones that are broken.
> chore: fix broken old status-im links

- libp2p/protocols/pubsub/pubsub.nim
This is needed for consistency with `addValidator` and also I came across compilation issue when using `removeValidator` from nwaku code base (`Error: 'scenario' is not GC-safe as it calls 'unsubscribe'`.)
> chore: add gcsafe pragma to removeValidator

- tests/pubsub/testgossipsubmeshmanagement.nim
- tests/pubsub/utils.nim
This PR tries to revive another stale PR with tests - [test(gossipsub): Topic Membership Tests](https://github.com/vacp2p/nim-libp2p/pull/1201) - which I just closed.
Actions taken:
- copied the tests from the original PR
- updated them to the latest conventions
- removed unnecessary tests:
- `"subscription limit test"` - test had a wrong assumption around the limit of the topic a local node can subscribe to and test logic itself was incorrect, another test around this already exist: https://github.com/vacp2p/nim-libp2p/blob/4d0b4ecc2217c669583d7e262a9e4b658fe6bcca/tests/pubsub/testgossipsubmessagehandling.nim#L113
- `"handle JOIN topic and mesh is updated"` - doesn't add anything new, repeats `"mesh and gossipsub populated when subscribed"`
- `"multiple peers join and leave topic …
> test(gossipsub): Topic Membership Tests - updated

- .pinned
- libp2p.nimble
- tests/stubs/torstub.nim
Require nim-stew version >= 0.4.0 rather than using `#head`, as per [@arnetheduck's comment](https://discord.com/channels/613988663034118151/740631022080622745/1371484042800664671) as well as this recommendation in the project's README file:
> ⚠️ No API/ABI stability - in applications, pick a commit and stick with it ⚠️
Obs: this can only be merged after the tag has been created on [nim-stew](https://github.com/status-im/nim-stew)
> chore: change nim-stew dep tagging

- libp2p.nim
- libp2p/protocols/connectivity/autonat/client.nim
- libp2p/protocols/connectivity/dcutr/client.nim
- libp2p/protocols/connectivity/dcutr/server.nim
- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/pubsub.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/protocols/pubsub/timedcache.nim
- libp2p/transports/wstransport.nim
- tests/commoninterop.nim
- tests/pubsub/testfloodsub.nim
- tests/pubsub/testgossipsubmessagehandling.nim
- tests/pubsub/utils.nim
- tests/testbufferstream.nim
- tests/testconnmngr.nim
- tests/testdiscovery.nim
- tests/testinterop.nim
- tests/testnative.nim
- tests/testrendezvous.nim
- tests/testwildcardresolverservice.nim
- tests/transports/tls/testcertificate.nim
- tests/utils/futures.nim
- change from deprecated `stew/results` to `results`
- remove unused imports, as reported by the compiler
> chore: fix import warnings

- tests/pubsub/testgossipsubmessagehandling.nim
**Note the 2 tests failed and issue #1208 is opened accordingly**
**Note:**  PR ready for review
test cases written according to test plan [here](https://www.notion.so/Gossipsub-651e02d4d7894bb2ac1e4edb55f3192d)
**Test "Check RPCMsg encoding"**  
1. create rpcMessage and encode it using encodeRpcMsg
2.  compare encoded message to encoded message generated from protoc cmd tool  version "libprotoc 3.21.12"
**Test "Check RPCMsg decoding"**
1. Use RPC message & encoded version of it generated from protoc cmd tool  version "libprotoc 3.21.12" as a reference
2. Check that decodeRpcMsg will decode the refernce RPC message successfully to the original version
> test(gossipsub): block5 protobuf test cases

- tests/hole-punching-interop/hole_punching.nim
- tests/transport-interop/main.nim
this pr adds timeout on `dial` to test theory if hole punching intepor test are failing due to dial hanging indefinitely.
reasons to support this theory:
- unit tests are hanging  #1377
- hp hanging clues (#1367):
-  the last message in logs is `Dialing peer`
- test ends after bit after 4min (there is timeout on total execution time to 4min)
-----------
second change, hp and transport interop tests have not correctly processed main future:
- should quit(0) if program is successful 
- after timeout there is no error message
> chore(hp): add timeout on dial

- .github/workflows/interop.yml
This reverts commit 2856db5490eea9d0595af09d8051ddcb40e4ae38.
riveting disabled zig from interrop test as issue is on nim-libp2p side. 
we should track to see if zig interop is working after fix is deployed.
> revert: disable transport interop with zig-v0.0.1 (#1372)

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/daily_common.yml
- README.md
- libp2p.nim
- libp2p/builders.nim
- tests/transport-interop/Dockerfile
Link for discussion: https://discord.com/channels/613988663034118151/740631022080622745/1374293099811176509
the newest nim-libp2p adds three extra runtime deps: libcrypto.so.3, libz.so.1, and libzstd.so.1. Using shared libraries is not really aligned with nimbus-eth2’s current design goals, which avoid unnecessary shared libs—especially since these don't bring clear benefits as Quic is currently not being used.
@arnetheduck described that one of the requirements is to static link everything, and openssl makes that needlessly painful. To sidestep this, we should transition to a statically-linkable crypto lib like aws-lc or boringssl (both have clean static builds out of the box:
- https://github.com/aws/aws-lc/blob/main/BUILDING.md
- …
> chore: make quic optional

- .github/workflows/dependencies.yml
we are having this error currently:
```
Invalid workflow file: .github/workflows/dependencies.yml#L20
The workflow is not valid. .github/workflows/dependencies.yml (Line: 20, Col: 20): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.ACTIONS_GITHUB_TOKEN_NIMBUS_ETH2 .github/workflows/dependencies.yml (Line: 23, Col: 20): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.ACTIONS_GITHUB_TOKEN_NWAKU
```
secrets could not be passed in matrix, and must be used from within job.
ci fixed proof: https://github.com/vacp2p/nim-libp2p/actions/workflows/dependencies.yml
> ci(dependencies): fix access to tokens

- .github/workflows/daily_common.yml
scheduled daily job was failing on `delete_cache` job. https://github.com/vacp2p/nim-libp2p/actions/runs/15385632375
this PR adds `continue-on-error` in case if this job fails, so we can continue with daily test job.
we ultimately only care about outcome of test job (if it succeeds with cache removed or not).
> fix(ci-daily): delete cache action will continue on error

- tests/testdaemon.nim
Issue: https://github.com/vacp2p/nim-libp2p/issues/1459
Changes:
- use `checkUntilTimeoutCustom(10.seconds, 100.milliseconds):` to bring back timeout value from before https://github.com/vacp2p/nim-libp2p/pull/1437
> test: increase timeout

- .github/workflows/daily_common.yml
This fixes a typo `testintegraion` -> `testintegration` that is causing daily actions to fail
> fix(daily): fix typo in testintegration

- libp2p/protocols/perf/client.nim
- tests/testnative.nim
- tests/testperf.nim
- adding stats to Perf client, needed by perf benchmarking implementation (https://github.com/libp2p/test-plans/pull/658)
- adding tests for Perf protocol
- discovered bug #1462
> feat(perf): add stats

- tests/pubsub/integration/testfloodsub.nim
- tests/pubsub/integration/testgossipsubcontrolmessages.nim
- tests/pubsub/integration/testgossipsubcustomconn.nim
- tests/pubsub/integration/testgossipsubfanout.nim
- tests/pubsub/integration/testgossipsubgossip.nim
- tests/pubsub/integration/testgossipsubheartbeat.nim
- tests/pubsub/integration/testgossipsubmeshmanagement.nim
- tests/pubsub/integration/testgossipsubmessagecache.nim
- tests/pubsub/integration/testgossipsubmessagehandling.nim
- tests/pubsub/integration/testgossipsubscoring.nim
- tests/pubsub/integration/testpubsubintegration.nim
- tests/pubsub/testbehavior.nim
- tests/pubsub/testgossipsub.nim
- tests/pubsub/testpubsub.nim
- tests/pubsub/testscoring.nim
Unit tests and integration tests in the PubSub folder are currently mixed together, which is not optimal.
Unit tests – these are related to individual methods and behaviors in isolation from the `PubSub/GossipSub` protocol, with minimal network simulation. They use direct method calls, usually without time-dependent assertions. For example:
https://github.com/vacp2p/nim-libp2p/blob/693cf944d8535251759d2279d40aae1ee755dd6b/tests/pubsub/testbehavior.nim#L148-L161
Integration tests – these involve spinning up 2 or more `FloodSub/GossipSub` nodes, focusing on complete message flows and peer interactions, usually with time-dependent assertions. For example:
https://github.com/vacp2p/nim-libp2p/blob/693cf944d8535251759d2279d40aae1ee755dd6b/tests/pubsub/integration/testgossipsubmeshmanagement.nim …
> test(gossipsub): split unit and integration tests

- libp2p/muxers/yamux/yamux.nim
- tests/testperf.nim
Fixes #1462
Even tho we do not handle half closed states correctly, i dived deeper into how [js-waku handles yamux closing a connection](https://github.com/ChainSafe/js-libp2p-yamux/blob/master/src/muxer.ts#L308) and noticed that streams are not reset there but closed instead, so implemented something similar while we refactor the connection abstractions.
> fix: force close of streams instead of reset when closing connection

- tests/testpeeridauth_integration.nim
Fixed wrong import on `testpeeridauth_integration.nim` that caused daily CI to fail: https://github.com/vacp2p/nim-libp2p/actions/runs/15817189298/job/44578136248#step:8:2345
> fix(peeridauth): fix peeridauth_integration import

- libp2p/muxers/yamux/yamux.nim
Fixes flaky test seen in https://github.com/vacp2p/nim-libp2p/actions/runs/15827052104/job/44609916834?pr=1470
Besides closing a channel, also mark them as reset so it's not possible to later call readOnce after a yamux session is closed, otherwise a StreamRemotelyClosed error is triggered while it should say StreamClosed as the closing happened locally first.
This is mostly a patch and should be fixed once proper half-closed stream state is added. (Because then it would be just a matter of reading whether `stream.readState == closed` is true or not (do note this attribute does not exist now)
> fix: mark channel as reset to not read after closed

- tests/pubsub/testgossipsub.nim
- tests/pubsub/utils.nim
Changes:
- add unit tests for Gossipsub `rpcHandler` around `rateLimit` and penalising peers with `punishInvalidMessage`:
- `"Peer is disconnected and rate limit is hit when overhead rate limit is exceeded"`
-  `"Peer is punished when message contains invalid sequence number"`
-  `"Peer is punished when message id generation fails"`
-  `"Peer is punished when signature verification fails"`
-  `"Peer is punished when message validation is rejected"`
> test(gossipsub): rpcHandler - rateLimit and punishInvalidMessage tests

- tests/pubsub/testbehavior.nim
Changes:
- organise GossipSub Behavior tests - rename and group by method
> test(gossipsub): organise Behavior tests 

- tests/pubsub/testbehavior.nim
- tests/pubsub/testgossipsub.nim
Changes:
- add unit tests for Gossipsub around `behaviourPenalty` (+1 test for `rateLimit`):
- `"handleGraft - penalizes direct peer attempting to graft"`
-  `"handleGraft - penalizes peer for grafting during backoff period"`
-  `"Peer is punished when decodeRpcMsg fails"`
-  `"Peer is punished and rate limit is hit when overhead rate limit is exceeded when decodeRpcMsg fails"`
-  `"Peer is disconnected and rate limit is hit when overhead rate limit is exceeded when decodeRpcMsg fails"`
> test(gossipsub):  behaviourPenalty tests

- tests/pubsub/testscoring.nim
Changes:
- add unit tests for GossipSub `updateScores`:
-`"Time in mesh scoring (P1)"`
-`"First message deliveries scoring (P2)"`
-`"Mesh message deliveries scoring (P3)"`
-`"Mesh failure penalty scoring (P3b)"`
-`"Invalid message deliveries scoring (P4)"`
-`"App-specific scoring"`
-`"Behaviour penalty scoring"`
-`"Colocation factor scoring"`
-`"Score decay to zero"`
-`"Peer stats expiration and eviction"`
-`"Combined scoring"`
-`"Zero topic weight skips scoring"`
> test(gossipsub): updateScores tests

- libp2p/autotls/acme/api.nim
- libp2p/autotls/acme/client.nim
- libp2p/autotls/acme/utils.nim
- libp2p/autotls/manager.nim
- libp2p/autotls/utils.nim
- libp2p/builders.nim
- libp2p/peeridauth/client.nim
- libp2p/peeridauth/mockclient.nim
- libp2p/switch.nim
- tests/testautotls.nim
- tests/testautotls_integration.nim
- tests/testpeeridauth_integration.nim
This adds the `AutoTLSManager` for downloading certificates, which uses [`ACMEClient`](https://github.com/vacp2p/nim-libp2p/pull/1470) (a wrapper around [`ACMEApi`](https://github.com/vacp2p/nim-libp2p/pull/1436)) and [`PeerIDAuthClient`](https://github.com/vacp2p/nim-libp2p/pull/1445)
~~**Obs**: this should only be merged after ACMEClient is merged: https://github.com/vacp2p/nim-libp2p/pull/1470 (will rebase when that is done).~~ This is ready for merging.
> feat(autotls): add AutoTLSManager

- libp2p/muxers/yamux/yamux.nim
- libp2p/utils/zeroqueue.nim
- tests/testnative.nim
- tests/testperf.nim
- tests/testzeroqueue.nim
this pr improves yamux performance by 20-40% as observed when running perf test. 
previously data was constantly appended to `recvQueue` which caused memory trashing due to resizing. 
change from this pr introduced `ZeroQueue` that will allow data to be appended and consumed with zero allocations.
> chore(yamux): improve performance with zero allocation queue

- tests/testautotls_integration.nim
- tests/testintegration.nim
Make `testintegration.nim` only be imported on amd64 (not i386)
- Daily CI (amd64): https://github.com/vacp2p/nim-libp2p/actions/runs/16000555195
- Daily CI (i386): https://github.com/vacp2p/nim-libp2p/actions/runs/16000560351
> fix(daily): testintegration only used on amd64

- tests/pubsub/testbehavior.nim
Changes:
- add unit tests for `GossipSub` `behaviour`:
- `"grafted - updates peer stats"`
- `"pruned - updates peer stats, applies penalty, and sets backoff"`
- `"handleBackingOff - removes expired backoff entries"`
- `"peerExchangeList - returns empty list when PX disabled"`
- `"peerExchangeList - returns filtered peers with SPR data"`
> test(gossipsub): behavior unit tests 2

- tests/pubsub/testgossipsub.nim
Changes:
- add unit tests for `GossipSub` `gossipsub`:
- `"onNewPeer - sets peer stats and budgets and disconnects if bad score"`
- `"onPubSubPeerEvent - StreamClosed removes peer from mesh and fanout"`
- `"onPubSubPeerEvent - DisconnectionRequested disconnects peer"`
- `"unsubscribePeer - handles nil peer gracefully"`
- `"unsubscribePeer - removes peer from mesh, gossipsub, fanout and subscribedDirectPeers"`
- `"unsubscribePeer - resets firstMessageDeliveries in peerStats"`
- `"unsubscribePeer - removes peer from peersInIP"`
- `"handleSubscribe via rpcHandler - subscribe and unsubscribe with direct peer"`
- `"handleSubscribe via rpcHandler - subscribe unknown peer"`
> test(gossipsub): gossipsub unit tests 1

- libp2p/cid.nim
- libp2p/crypto/crypto.nim
- libp2p/crypto/ecnist.nim
- libp2p/crypto/minasn1.nim
- libp2p/crypto/rsa.nim
- libp2p/crypto/secp.nim
- libp2p/daemon/daemonapi.nim
- libp2p/multiaddress.nim
- libp2p/multibase.nim
- libp2p/nameresolving/dnsresolver.nim
- libp2p/peerid.nim
- libp2p/protobuf/minprotobuf.nim
- libp2p/protocols/kademlia/routingtable.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- libp2p/transports/tls/certificate.nim
- libp2p/utils/zeroqueue.nim
utilizing `newSeqUninitialized` instead of `newSeq` to gain bit more performance when initializing sequences.
in this pr,  `newSeqUninitialized` is utilized only in places where it can directly replace `newSeq` without any change to other logic.
> chore: utilizing newSeqUninitialized

- README.md
- libp2p.nimble
- libp2p/autotls/acme/api.nim
- libp2p/autotls/acme/client.nim
- libp2p/autotls/service.nim
- libp2p/autotls/utils.nim
- libp2p/builders.nim
- tests/testintegration.nim
- tests/testnative.nim
Adds a `-d:libp2p_autotls_support` flag to enable the usage of AutoTLS
As suggested by @arnetheduck, we're disabling this feature, as any additional dependency is a potential security issue.
cc: @tersec
> chore: hide autotls under compile flag

- libp2p/protocols/perf/client.nim
- libp2p/protocols/perf/server.nim
- tests/testperf.nim
**What**
Fixed QUIC transport compatibility with perf protocol.
- Move connection close after read phase for TCP
- Add timeout-based read for QUIC streams
- Fix infinite read loop with proper EOF detection
- Make QUIC calls conditional on support flag
**Why**
QUIC doesn't support half-close like TCP transports. Perf was closing connection
after write but before read, breaking QUIC streams with "stream is closed" errors.
Now both QUIC and TCP transports work correctly with perf protocol.
**Links**
Issue [1482](https://github.com/vacp2p/nim-libp2p/issues/1482)
> fix(perf): add QUIC transport compatibility

- libp2p/transports/quictransport.nim
node using quic transport was crashing with:
```
Unhandled defect: [Connection.getWrapped] abstract method not implemented! [AssertionDefect]
```
because `QuicStream` did not had `getWrapped` method specified
> fix(quic): add getWrapped method for QuicStream

- libp2p/autotls/acme/api.nim
- libp2p/autotls/acme/client.nim
- libp2p/autotls/acme/utils.nim
- libp2p/autotls/mockservice.nim
- libp2p/autotls/service.nim
- libp2p/autotls/utils.nim
- libp2p/builders.nim
- libp2p/dialer.nim
- libp2p/peerinfo.nim
- libp2p/protocols/connectivity/relay/rtransport.nim
- libp2p/switch.nim
- libp2p/transports/memorytransport.nim
- libp2p/transports/quictransport.nim
- libp2p/transports/tcptransport.nim
- libp2p/transports/tls/certificate.c
- libp2p/transports/tls/certificate.h
- libp2p/transports/tls/certificate_ffi.nim
- libp2p/transports/tortransport.nim
- libp2p/transports/transport.nim
- libp2p/transports/wstransport.nim
- tests/testautotls.nim
- tests/testintegration.nim
- tests/testwstransport.nim
- tests/testwstransport_integration.nim
- tests/transports/tls/testcertificate.nim
Use autotls installed certificates in `wstransport`.
> feat(wstransport): add autotls support

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/gossipsub/behavior.nim
- tests/pubsub/testpreamblestore.nim
Typo was making [coverage tests](https://github.com/vacp2p/nim-libp2p/actions/runs/16417473361/job/46386856516?pr=1561) fail:
```
/home/runner/work/nim-libp2p/nim-libp2p/libp2p/protocols/pubsub/gossipsub/behavior.nim(951, 41) Error: undeclared field: 'startAt=' for type types.PreambleInfo [type declared in /home/runner/work/nim-libp2p/nim-libp2p/libp2p/protocols/pubsub/gossipsub/types.nim(75, 3)
```
> fix: typo on startAt

- README.md
- flake.lock
- flake.nix
Not much: only adds the openssl dependencies needed.
I have my nim and nimble requirements setup in my system configuration, hence why it's not in here.
For now, this is only really useful for _me_, but it can eventually becoming a powerful tool.
For example, with tho go daemon dependency, if that is put into the flake for a testing shell, anyone with a `nix` package manager (not neccisarily nixos), would be able to run `nix develop testing`, or something to that effect, and everything is automagically ready to run `nimble test`: all the dependencies (openssl, nim, nimble, go deamon, etc) are _just there_
> chore(ci): initial flake.nix file with dev shell

- libp2p/autotls/service.nim
- libp2p/autotls/utils.nim
This will keep clients such as `nimbus` from having to vendor [`dnsclient.nim`](https://github.com/ba0f3/dnsclient.nim) unless they're using autotls (i.e. using `-d:libp2p_autotls_support`)
> chore(autotls): only import dnsclient when autotls is required

- libp2p/muxers/yamux/yamux.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
- tests/testyamux.nim
This PR aims to avoid endlessly keep allocating memory when publishing. See [this](https://github.com/waku-org/nwaku/issues/3496#issuecomment-3102867775) for details.
There are some style/nitpick changes but the ones that give real impact to memory consumption are:
- Addition of `channel.clearQueues()` in yamux.nim `readOnce` methods
-  Replace `channel.sendQueue.keepItIf(not (it.fut.cancelled() and it.sent == 0))` with `channel.sendQueue.keepItIf(not it.fut.finished())`
This PR is fundamentally inspired by the following @NagyZoltanPeter 's comment: https://github.com/vacp2p/nim-libp2p/pull/1540#issuecomment-3071666756. So kudos to you my friend if we manage to merge it :partying_face: :raised_hands: 
---
Follow these instructions: …
> fix: memory consumption in yamux and pubsubpeer

- libp2p/muxers/yamux/yamux.nim
- libp2p/protocols/pubsub/pubsubpeer.nim
This PR is motivated by: 
https://github.com/vacp2p/nim-libp2p/pull/1570#discussion_r2228640214 --> Cleanup `libp2p/protocols/pubsub/pubsubpeer.nim`. There's no need to check the `failed` field in a `raw` future because `await` already extracts the exception in `try: await rawFut except`. 
https://github.com/vacp2p/nim-libp2p/pull/1570#discussion_r2228646674 --> Make `sendLoop` more secure and make sure it doesn't throw any exception
> fix: more secure send loop in yamux and exception-handling-code cleanup in pubsubpeer

- .github/actions/install_nim/action.yml
- .github/workflows/ci.yml
- .github/workflows/daily_amd64.yml
- .github/workflows/daily_i386.yml
- .github/workflows/examples.yml
- .pinned
- README.md
- examples/circuitrelay.nim
- examples/directchat.nim
- examples/helloworld.nim
- examples/tutorial_1_connect.nim
- examples/tutorial_2_customproto.nim
- examples/tutorial_3_protobuf.nim
- examples/tutorial_4_gossipsub.nim
- examples/tutorial_5_discovery.nim
- examples/tutorial_6_game.nim
- interop/hole-punching/Dockerfile
- interop/transport/Dockerfile
- libp2p.nimble
- libp2p/multistream.nim
- libp2p/transports/quictransport.nim
Since nimbus, waku and codex (which are our most important clients) no longer support nim 1.6, as, we hope, most of our users also have, we've decided to drop support for nim 1.6.
> chore: remove support for nim 1.6

- performance/.gitignore
- performance/Dockerfile
- performance/main.nim
- performance/runner.sh
- performance/scenarios.nim
- performance/utils.nim
This PR is a follow up to the https://github.com/vacp2p/nim-libp2p/pull/1544 - it contains refactored base scenario with a test runner.
**What’s included?**
- **Dockerfile**:
- Installs dependencies and compiles the node test logic
- **Test runner**:
- Spins up multiple Docker containers (each running a `nim-libp2p` node with the test script).
- Cleans up containers and output files before and after each run.
- **Node test logic**:
- Configures each GossipSub node.
- Handles peer discovery, connection, and message publishing.
- Measures message delivery latency (in milliseconds, with microsecond resolution) for each node.
- Collects per-node stats: messages sent/received, latency (min/max/avg).
- Writes results to a JSON file for aggregation after the test run.
```bash
docker build -f …
```
> test(gossipsub): Performance tests - base scenario and runner

- libp2p/muxers/muxer.nim
- libp2p/peerstore.nim
- libp2p/stream/connection.nim
- libp2p/transports/quictransport.nim
closes: [#1606](https://github.com/vacp2p/nim-libp2p/issues/1606)
> fix(quic): setting shortAgent

- tests/pubsub/integration/testgossipsubmeshmanagement.nim
because it's vary flaky with quic
> chore(pubsub): simplify prune backoff test

- libp2p/transports/quictransport.nim
- `not self.listener.isNil call start() before calling accept() [AssertionDefect]` 
can happen when server is being stopped, and still accepting, so this `doAssert` was moved below `if not self.running:` as sanity check 
- `the length of the seq changed while iterating over it [AssertionDefect]`
can happen when connection is stopped with transport; so connection's onClose callback is modifying transport.connection while stop() is iterating of connections.
> fix(quic): race errors when stopping transport

- libp2p/errors.nim
- libp2p/transports/wstransport.nim
> fix: don't check for errors as `close()` will only contain futures that raise `[]`

- libp2p/muxers/yamux/yamux.nim
> fix: compilation warning on yamux due to using `CatchableErr`

- libp2p/protocols/pubsub/gossipsub.nim
- libp2p/protocols/pubsub/rpc/message.nim
- tests/pubsub/testmessage.nim
Fixing pubsub signature verification as per [the spec](https://github.com/libp2p/specs/blob/0caf71bb29a525ab0ef14ea4511d68e873d4a2d9/pubsub/README.md?plain=1#L215-L216)
> fix: pubsub signature verification

- tests/testyamux.nim
- tests/utils/futures.nim
Changes:
- add new test suite for Yamux: `Frame handling and stream initiation`
- new tests:
- `"Ping Syn responds Ping Ack"`
- `"Go Away Status responds with Go Away"`
- 2x `"Syn opens stream and sends Ack"`
- Data header
- WindowUpdate header
- 5x `"Reject invalid/unknown header"`
- Reserved parity on Data+Syn (even id against responder)
- Reserved stream id 0
- First frame missing Syn on unopened stream
- Reserved parity on WindowUpdate+Syn (even id against responder)
- Unknown stream WindowUpdate without Syn
- `"Flush unknown-stream Data up to budget then ProtocolError when exceeded"`
> test(yamux): Add unit tests - frame handling and stream initiation

- libp2p/protocols/kademlia/kademlia.nim
It is recommended to review this PR with whitespace ignored, as much of it is just changing indentation due to removal of a try scope.
This PR goes through kademlia.nim and attempts to move use of exceptions towards zero. There are still some left, but they are either CancelledError (which is super non-trivial to get rid of), or the dispatchputvalue function. It's late, and I'm not too far from going on holiday, so I thought it appropriate to at least get te content of this PR done, and can come back to that later.
> refactor: Refine, and reduce, exception scope

- .github/workflows/performance.yml
This task is causing the repo to be 500mb to clone.
Disabling the task temporarily while we find out where to put the performance plots
> chore: temporarily disable performance plots from being published

- libp2p/muxers/mplex/mplex.nim
- libp2p/muxers/yamux/yamux.nim
- libp2p/protocols/secure/noise.nim
- libp2p/protocols/secure/secure.nim
Follow up to https://github.com/vacp2p/nim-libp2p/pull/1651 which also passed `localAddr` in Mplex, Yamux and Noise.
> chore: pass localAddr in noise, mplex and yamux

- libp2p/protocols/rendezvous.nim
- tests/discovery/testrendezvous.nim
Changes:
- small refactor of `rendezvous`:
- use constants in the TTL validation
- add `MinimumAcceptedDuration` constant and comments explaining the difference between `MinimumDuration`
- rename `defaultDT` into `expiredDT` to reflect better it's function in marking records as expired
- new tests:
- `"Peer default TTL is saved when advertised"`
- `"Peer TTL is saved when advertised with TTL"`
- `"Peer can reregister to update its TTL before previous TTL expires"`
> test(rendezvous): Registration TTL tests

- .github/workflows/linters.yml
- libp2p/protocols/pubsub/pubsubpeer.nim
Use https://github.com/arnetheduck/nph-action/pull/1 to work around [reviewdog's bug](https://github.com/reviewdog/action-suggester/pull/98) until they release a new version with the fix.
> fix(linters): use workaround for reviewdog bug

- libp2p/protocols/connectivity/autonatv2/client.nim
nimbus-eth2 CI complains otherwise
```
2025-09-12T19:29:10.1341407Z /github-runner/github-runner-node-01/workspace/nimbus-eth2/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/connectivity/autonatv2/client.nim(36, 19) Error: undeclared identifier: 'Table'
2025-09-12T19:29:10.1342866Z candidates (edit distance, scope distance); see '--spellSuggest': 
2025-09-12T19:29:10.1343438Z  (3, 2): 'File'
2025-09-12T19:29:10.1343776Z  (3, 2): 'Page'
2025-09-12T19:29:10.1344074Z  (3, 2): 'Pause'
2025-09-12T19:29:10.2258408Z make: *** [Makefile:451: ncli_testnet] Error 1
```
cc: @tersec @jakubgs
> chore: add missing import

- config.nims
- group `warningAsError` together
- `# begin Nimble config (version 2)` changes is always made when doing `nimble setup -l` so why not have it always
> chore: nimble config tidy

- tests/testautotls_integration.nim
https://github.com/vacp2p/nim-libp2p/actions/runs/17876578854/job/50838745472
> fix: add missing import for linux/amd64 daily job

- README.md
I noticed there’s a broken link.
> chore(readme): Update chat code example link

- libp2p/builders.nim
- libp2p/muxers/yamux/yamux.nim
While discussing the usage of close/closeWithEOF with @NagyZoltanPeter, i realized that we werent enforcing correctly the max channel count due to passing the windowSize in the wrong parameter order. This meant that in practice we would be able to create a max of 256000 streams.
This PR fixes this, however, it means that nwaku will need to add `close` / `closeWithEOF` wherever a stream is being used, otherwise the app is going to quickly run into exceptions due to too many channels being opened, because of the 200 streams limit. ~~**This max number of streams is global, not per peer.**~~ 
**EDIT**: as described by @NagyZoltanPeter [it's per peer, not global](https://github.com/vacp2p/nim-libp2p/pull/1724#issuecomment-3342084488)
cc: @vacp2p/waku 
Streams in libp2p are not reused. The only …
> fix: invalid parameter passed in builder being used as channel count size
