.travis.yml
libp2p/crypto/crypto.nim
libp2p/crypto/ed25519/ed25519.nim
libp2p/daemon/daemonapi.nim
libp2p/multihash.nim
tests/testcrypto.nim

Add PublicKey and Signature types to daemonapi.
Add more tests for crypto.nim

Fix import bugs.

---

libp2p/connection.nim
libp2p/peer.nim
libp2p/peerinfo.nim
libp2p/protocols/identify.nim
libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/protocols/pubsub/rpc/message.nim
libp2p/protocols/pubsub/timedcache.nim
libp2p/protocols/secure/secio.nim
libp2p/switch.nim
tests/pubsub/testgossipsub.nim
tests/pubsub/utils.nim
tests/testidentify.nim
tests/testinterop.nim
tests/testmultistream.nim
tests/testnative.nim
tests/testpeerinfo.nim
tests/testswitch.nim

extract public and private keys fields from peerid

---

libp2p.nimble
libp2p/connection.nim
libp2p/multistream.nim
libp2p/muxers/mplex/mplex.nim
libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/protocols/secure/secio.nim
libp2p/standard_setup.nim
libp2p/stream/bufferstream.nim
tests/pubsub/testfloodsub.nim
tests/pubsub/testgossipsub.nim
tests/pubsub/utils.nim
tests/testswitch.nim

This depends on https://github.com/status-im/nim-chronos/pull/63

Adding timeouts

---

libp2p/connection.nim

Exception needs to be re-raised in `readLp`.

fix: reraise exception in readLp

---

libp2p/connection.nim
libp2p/muxers/mplex/lpchannel.nim
libp2p/muxers/mplex/mplex.nim
libp2p/muxers/muxer.nim
tests/testmplex.nim

See https://github.com/status-im/nim-libp2p/pull/76

Lazy channels

---

libp2p/connection.nim
libp2p/muxers/mplex/mplex.nim
tests/testmplex.nim

See https://github.com/status-im/nim-libp2p/pull/74

Mplex timeout & size limits

---

libp2p/stream/bufferstream.nim
tests/testbufferstream.nim

Don't lockup on close

---

libp2p/muxers/mplex/coder.nim
libp2p/muxers/mplex/lpchannel.nim
libp2p/muxers/mplex/mplex.nim

fix: use exact types for mplex id

---

libp2p/connection.nim
libp2p/protocols/secure/secio.nim
tests/testswitch.nim

Also fix secio fragments + test

Allow to specify a read size in readLp

---

tests/testnoise.nim
tests/testswitch.nim

Could not repro locally yet.
Merging to make tests again green until I figure out the issue for now.

Disable new fragmentation tests

---

libp2p.nimble
tests/testnoise.nim
tests/testswitch.nim

Nim was bumped so chronicles was failing

Fix CI, chronicles bump

---

libp2p/muxers/mplex/coder.nim
tests/testmplex.nim

@arnetheduck you were asking about this
@dryajov I think it's fine to allow mplex to send fragmented payloads no?

Mplex: Add the ability to send any size payload

---

.travis.yml
azure-pipelines.yml
libp2p.nimble
libp2p/connection.nim
libp2p/protocols/secure/secio.nim
libp2p/stream/bufferstream.nim
libp2p/stream/lpstream.nim

debug prints

---

libp2p/crypto/crypto.nim
libp2p/crypto/ecnist.nim
libp2p/crypto/minasn1.nim
libp2p/crypto/rsa.nim
tests/testecnist.nim
tests/testrsa.nim

So far rsa.nim is done, tests pass but ignore the way it looks because that needs Result as well basically

Use Result construct in minasn1

---

libp2p/multiaddress.nim
tests/testmultiaddress.nim

Add MultiAddress.init(integer) for tcp,udp,dccp,sctp protocols.

---

libp2p.nimble
libp2p/protocols/secure/noise.nim
libp2p/protocols/secure/secure.nim
libp2p/standard_setup.nim
libp2p/switch.nim

Also added noise to pubsub tests

Fix secure/noise by securing explicitly

---

libp2p/connection.nim
libp2p/muxers/mplex/lpchannel.nim
libp2p/protocols/secure/noise.nim
libp2p/protocols/secure/secio.nim
libp2p/protocols/secure/secure.nim
libp2p/stream/bufferstream.nim
libp2p/stream/chronosstream.nim
libp2p/stream/lpstream.nim
libp2p/stream/streamseq.nim
tests/testbufferstream.nim
tests/testinterop.nim
tests/testmultistream.nim
tests/testnative.nim
tests/testnoise.nim
tests/teststreamseq.nim

#118 read loop simplification for secure

remove readLoop in secure protocols

---

libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim
tests/pubsub/testgossipsub.nim

I think this PR covers both
https://github.com/status-im/nim-libp2p/issues/153
and
https://github.com/status-im/nim-libp2p/issues/155

Add PubSub observer+ hooks (they can modify as well)

---

docs/GETTING_STARTED.md
docs/tutorial/directchat/second.nim
docs/tutorial/second.nim
examples/directchat.nim
libp2p/connection.nim
libp2p/multistream.nim
libp2p/muxers/mplex/coder.nim
libp2p/muxers/mplex/types.nim
libp2p/protocols/identify.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/stream/lpstream.nim
tests/pubsub/testfloodsub.nim
tests/pubsub/testgossipinternal.nim
tests/pubsub/testgossipsub.nim
tests/pubsub/testmcache.nim
tests/testinterop.nim
tests/testmplex.nim
tests/testmultistream.nim
tests/testnoise.nim
tests/testswitch.nim

* fixes #111
* fixes remote varint size exploit in identify

fix varint issues

---

libp2p/stream/lpstream.nim
tests/testbufferstream.nim
tests/testmplex.nim
tests/testnoise.nim
tests/testtransport.nim

remove `read` in favor of `readExactly` in most places

Remove read

---

libp2p/errors.nim
libp2p/muxers/mplex/coder.nim
tests/pubsub/testfloodsub.nim
tests/testinterop.nim
tests/testmplex.nim
tests/testswitch.nim

Some minor cleanup product of #174, mostly tests and logging.

Cleanup - tests and logging

---

libp2p/crypto/chacha20poly1305.nim
libp2p/crypto/curve25519.nim
libp2p/protocols/secure/noise.nim

They were left overs from crypto.nim refactor

Use results and no exceptions in chacha and curve25519

---

libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/protocols/pubsub/rpc/protobuf.nim
libp2p/protocols/secure/secure.nim
tests/pubsub/testfloodsub.nim
tests/pubsub/testgossipinternal.nim
tests/pubsub/testgossipsub.nim
tests/pubsub/utils.nim

This should fix issues with gossipsub, where it wouldn't collect enough peers to gossip. This is part one of a couple of more changes, including #181. This can be merged without #181, but it relies on it to be fully functional.

gossipsub fixes

---

libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/pubsub/rpc/message.nim
libp2p/protocols/pubsub/rpc/protobuf.nim
libp2p/switch.nim
tests/pubsub/testgossipsub.nim
tests/pubsub/testmcache.nim
tests/pubsub/testmessage.nim
tests/pubsub/testpubsub.nim
tests/testidentify.nim
tests/testnoise.nim
tests/testpeerinfo.nim
tests/testswitch.nim

Gossipsub interop

---

examples/directchat.nim
libp2p/cid.nim
libp2p/crypto/secp.nim
libp2p/daemon/daemonapi.nim
libp2p/multiaddress.nim
libp2p/multibase.nim
libp2p/multihash.nim
libp2p/protobuf/minprotobuf.nim
libp2p/protocols/identify.nim
libp2p/standard_setup.nim
libp2p/stream/lpstream.nim
libp2p/transcoder.nim
libp2p/transports/tcptransport.nim
libp2p/transports/transport.nim
libp2p/varint.nim
libp2p/vbuffer.nim
libp2p/wire.nim
tests/testidentify.nim
tests/testinterop.nim
tests/testmplex.nim
tests/testmultiaddress.nim
tests/testmultibase.nim
tests/testmultistream.nim
tests/testnoise.nim
tests/testswitch.nim
tests/testtransport.nim
tests/testvarint.nim

Mostly around `varint` and `vbuffer`

Less exceptions more results

---

examples/directchat.nim
libp2p.nimble
libp2p/muxers/mplex/coder.nim
libp2p/protocols/secure/noise.nim
libp2p/protocols/secure/secio.nim
libp2p/standard_setup.nim
libp2p/switch.nim
tests/testinterop.nim
tests/testnoise.nim
tests/testswitch.nim

Also indeed giving priority to noise for testing

Secure managers are now sorted, giving priority to noise

---

libp2p/muxers/mplex/lpchannel.nim
libp2p/muxers/mplex/mplex.nim
libp2p/muxers/muxer.nim
libp2p/switch.nim
tests/testswitch.nim

Add proper peer lifetime handling

Close peers

---

libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/switch.nim
tests/pubsub/testfloodsub.nim
tests/pubsub/testgossipinternal.nim
tests/pubsub/testgossipsub.nim
tests/pubsub/utils.nim
tests/testbufferstream.nim
tests/testmplex.nim
tests/testmultistream.nim
tests/testnoise.nim
tests/testswitch.nim

add sparse message propagation tests to gossipsub
remove `all` from tests

add sparse message propagation tests to gossipsub

---

libp2p/multistream.nim
libp2p/muxers/mplex/coder.nim
libp2p/muxers/mplex/mplex.nim
libp2p/protocols/pubsub/rpc/message.nim
tests/pubsub/testfloodsub.nim
tests/pubsub/testgossipsub.nim
tests/pubsub/testmcache.nim
tests/testbufferstream.nim
tests/testinterop.nim
tests/testmultistream.nim
tests/testnoise.nim
tests/testtransport.nim

use `.toBytes` and `fromBytes` instead of casts

Remove casts

---

libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/protocols/pubsub/rpc/message.nim
libp2p/utility.nim

In order to visualize it's functionality
Still WIP

Start adding some metrics to pubsub

---

libp2p/multistream.nim
libp2p/protocols/identify.nim
libp2p/switch.nim

close streams

---

libp2p/standard_setup.nim

much fewer peers on witti with noise first

secio then noise

---

libp2p/muxers/mplex/lpchannel.nim
libp2p/peerinfo.nim
libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/switch.nim

disconnect-ps-peer and add metrics for connects and disconnects

remove pubsub peer on disconnect

---

libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim

hadren table access to prevent subtle key not found or iter modified errors

fixing some key not found exceptions

---

libp2p/multistream.nim
libp2p/switch.nim
tests/testmultistream.nim
tests/testnative.nim

but rather empty string if all fails
Also re-enable tests

multistream select make sure to not report NA

---

libp2p/muxers/mplex/mplex.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/protocols/secure/noise.nim
libp2p/protocols/secure/secio.nim
libp2p/protocols/secure/secure.nim
libp2p/stream/chronosstream.nim
libp2p/stream/connection.nim
libp2p/stream/lpstream.nim
libp2p/switch.nim
tests/pubsub/testgossipsub.nim
tests/testinterop.nim
tests/testswitch.nim

Add concurrent dials support and better connection tracking for incoming out/outgoing connections. 
Closes #236.

Concurrent dials

---

libp2p/crypto/curve25519.nim
libp2p/crypto/ecnist.nim
libp2p/protocols/secure/noise.nim
libp2p/protocols/secure/secure.nim
libp2p/stream/streamseq.nim

* clear secrets explicitly
* simplify keygen
* avoid some trivial memory allocations
* fix little endian encoding of nonce

noise updates

---

libp2p/muxers/mplex/lpchannel.nim
libp2p/stream/bufferstream.nim
libp2p/stream/lpstream.nim

Drain the channel on both close and reset.
closes #262

Drain buffer

---

libp2p/connmanager.nim
libp2p/peerinfo.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/stream/bufferstream.nim
libp2p/stream/connection.nim
libp2p/stream/lpstream.nim
libp2p/switch.nim
tests/testconnmngr.nim
tests/testswitch.nim

Move connection management out of switch into it's own module

Connection manager

---

examples/directchat.nim
libp2p/muxers/mplex/lpchannel.nim
libp2p/muxers/mplex/mplex.nim
libp2p/muxers/muxer.nim
libp2p/standard_setup.nim
libp2p/switch.nim
tests/testinterop.nim
tests/testmplex.nim
tests/testnoise.nim
tests/testswitch.nim

Channel timeout

---

libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/switch.nim

as requested by @tersec to be used in NBC.
* Add a `unsubscribeAll` procedure.
* Fix a few issues in the existing `unsubscribe`

Fix some unsubscribe issues and add unsubscribeAll helper

---

libp2p/muxers/mplex/lpchannel.nim

Solves some possible confusion when debugging/tracing

Handle cancellation in timeoutMonitor

---

libp2p/muxers/mplex/lpchannel.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/standard_setup.nim
libp2p/switch.nim
tests/pubsub/testfloodsub.nim
tests/pubsub/testgossipsub.nim
tests/pubsub/utils.nim
tests/testinterop.nim

This changes the pubsub subscribe flow and requires changes in nbc to be merged
The hooks changes where already covered by https://github.com/status-im/nim-libp2p/pull/288

Pubsub lifetime

---

libp2p/connmanager.nim
libp2p/switch.nim

collections may change while doing await

resolve several races in connmanager

---

.github/workflows/nbc.yml

Using this: https://github.com/peter-evans/create-pull-request
I add to make a Github App in order to authorize it here: https://github.com/apps/nbc-bump-bot (details here https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens and https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs)

Automatic NBC bump PRs

---

azure-pipelines.yml

so the latest Nim compiler version can be cached

Azure: bump NimBinaries cache key

---

libp2p/errors.nim
libp2p/muxers/mplex/coder.nim
libp2p/muxers/mplex/lpchannel.nim
libp2p/muxers/mplex/mplex.nim
libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/stream/chronosstream.nim
libp2p/switch.nim
libp2p/transports/tcptransport.nim
tests/testmplex.nim

Fix build, add some raises

---

libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsub.nim

@dryajov this seems to fix the gossipsub table.
I think it is correct to apply the same rule to sub types

Fix subclass calls to handleDisconnect

---

libp2p/crypto/crypto.nim
libp2p/crypto/ecnist.nim
libp2p/crypto/ed25519/ed25519.nim
libp2p/crypto/minasn1.nim
libp2p/crypto/rsa.nim

Fixes https://github.com/status-im/nim-libp2p/issues/300

Use constant-time hex encoding/decoding procedures explicitly.

---

libp2p/crypto/minasn1.nim
tests/testminasn1.nim
tests/testnative.nim

Fixes https://github.com/status-im/nim-libp2p/issues/296

Refactor minasn1 and fix security issues.

---

libp2p/muxers/mplex/coder.nim
libp2p/muxers/mplex/lpchannel.nim
libp2p/muxers/mplex/mplex.nim
libp2p/muxers/mplex/types.nim
libp2p/stream/bufferstream.nim

* less async
* less copying of data
* less redundant cleanup

simplify mplex

---

libp2p/protocols/pubsub/pubsubpeer.nim

For more details, see the added commend in `getSendConn`

Restore interop with Lighthouse by preventing concurrent meshsub dials

---

libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/mcache.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/protocols/pubsub/timedcache.nim
tests/pubsub/testmcache.nim
tests/pubsub/testpubsub.nim
tests/pubsub/testtimedcache.nim

* remove timed cache - the window shifting already removes old messages
* ref -> object
* avoid unnecessary allocations with `[]` operator

gossipsub / floodsub fixes

---

examples/directchat.nim
libp2p/connmanager.nim
libp2p/daemon/daemonapi.nim
libp2p/muxers/mplex/coder.nim
libp2p/muxers/mplex/lpchannel.nim
libp2p/muxers/mplex/mplex.nim
libp2p/muxers/muxer.nim
libp2p/peerid.nim
libp2p/peerinfo.nim
libp2p/protocols/identify.nim
libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/protocols/pubsub/rpc/message.nim
libp2p/protocols/pubsub/rpc/messages.nim
libp2p/protocols/pubsub/rpc/protobuf.nim
libp2p/protocols/secure/noise.nim
libp2p/protocols/secure/secio.nim
libp2p/protocols/secure/secure.nim
libp2p/stream/bufferstream.nim
libp2p/stream/chronosstream.nim
libp2p/stream/connection.nim
libp2p/switch.nim
tests/pubsub/testgossipsub.nim
tests/testpeer.nim

* use short format for logging peerid
* log peerid:oid for connections

simplify and unify logging

---

libp2p/connmanager.nim
libp2p/muxers/mplex/lpchannel.nim
libp2p/muxers/mplex/mplex.nim

* close the right connection when channel send fails
* don't crash on channel id that is not unique

mplex fixes

---

libp2p/connmanager.nim
libp2p/multistream.nim
libp2p/muxers/mplex/lpchannel.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/stream/connection.nim
libp2p/stream/streamseq.nim
libp2p/switch.nim

In particular, allow longer multistream select reads

logging fixes and small cleanups

---

libp2p/connmanager.nim
libp2p/switch.nim

Moving connection & peer events to connection manager, to prepare for upcoming connection management rework.

move events to conn manager

---

azure-pipelines.yml
libp2p.nimble
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/pubsub/rpc/message.nim
tests/pubsub/testfloodsub.nim
tests/pubsub/testgossipsub.nim
tests/pubsub/utils.nim

defaultMsgIdProvider fixes when anonymize is on
test anonymize
various bug fixing

defaultMsgIdProvider alternative/test anonymize

---

libp2p/protocols/pubsub/rpc/protobuf.nim

https://github.com/status-im/nim-libp2p/issues/365
https://github.com/status-im/nim-libp2p/issues/388
https://github.com/status-im/nim-libp2p/issues/349

Gossip 1.1 further features and tests

---

libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/gossipsub10.nim
libp2p/protocols/pubsub/pubsub.nim
tests/pubsub/testfloodsub.nim
tests/pubsub/testgossipsub.nim

Gossip 1.1 spec's extended validation

Extended validators

---

libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/gossipsub10.nim

Fixes a silly mistake in extended validation

fix validation according to specification

---

libp2p/muxers/mplex/lpchannel.nim
libp2p/muxers/mplex/mplex.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/secure/secure.nim
libp2p/stream/bufferstream.nim
libp2p/stream/chronosstream.nim
libp2p/stream/connection.nim
libp2p/stream/lpstream.nim
libp2p/switch.nim
libp2p/transports/tcptransport.nim

Attempting to fix channel leaks reported in #393.

Channel leaks

---

libp2p/crypto/ecnist.nim
libp2p/multiaddress.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsub.nim
tests/pubsub/testgossipsub.nim

gossipsub audit fixes

---

libp2p/protocols/secure/secure.nim
libp2p/stream/bufferstream.nim
libp2p/stream/chronosstream.nim
libp2p/stream/connection.nim
libp2p/stream/lpstream.nim
libp2p/transports/tcptransport.nim
libp2p/transports/transport.nim

re-adding split counts for streams

split stream counts by direction

---

libp2p/connmanager.nim
libp2p/protocols/identify.nim
libp2p/stream/chronosstream.nim
libp2p/switch.nim
libp2p/transports/tcptransport.nim

Moving peer events int connmanager

Move triggers

---

tests/testmplex.nim

Test showing read failure on cancel

read failure

---

libp2p/muxers/mplex/lpchannel.nim
libp2p/stream/bufferstream.nim
libp2p/stream/connection.nim
libp2p/stream/lpstream.nim
tests/testbufferstream.nim
tests/testmplex.nim

silly for loop..
* allow only one concurrent read
* fix mplex test race condition
* add some bufferstream eof tests

fix channels not being reset

---

libp2p/protocols/secure/noise.nim
libp2p/protocols/secure/secio.nim

Integrating some more unrelated changes from `tcp-limits2`.

update conn peerinfo instead of replacing

---

libp2p/connmanager.nim
libp2p/switch.nim
tests/testconnmngr.nim

getMuxedStream to more appropriate getStream

---

libp2p/muxers/mplex/mplex.nim
libp2p/protocols/secure/secure.nim

fixing log level to avoid scaring users

---

libp2p/protocols/identify.nim
tests/helpers.nim
tests/testidentify.nim

Allow custom identify agent string

---

libp2p/protocols/pubsub/gossipsub.nim

Add missing cache parameter, might be critical for beacon chain

expose seenTTL parameters

---

libp2p/protocols/pubsub/gossipsub.nim

Sadly so far those fixes matter little without scores

Some gossip fixes

---

libp2p/peerid.nim
libp2p/protocols/pubsub/mcache.nim
tests/testnative.nim
tests/testpeerid.nim

* fix dangling cstring on error return
* remove some useless inlines
* less mallocs in shortlog
* proc -> func
* rename test

clean up peerid

---

libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim

Workaround the gossipsub table race condition

---

libp2p/protocols/secure/noise.nim

simplify noise frame construction

---

libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/switch.nim
tests/pubsub/testgossipinternal.nim
tests/pubsub/testgossipsub.nim

* cleanup unused `connections` seq
* add a flag to disconnect very bad peers in score terms

Gossipsub wip

---

libp2p/protocols/pubsub/gossipsub.nim

Simplify and improve stats scoring

Gossipsub peertable fixes

---

libp2p/peerstore.nim
tests/testpeerstore.nim

This is fairly innocuous as it isn't being used internally by libp2p right now. However, other projects such as waku and potentially dagger, are already depending on it.

Merge unstable

---

libp2p.nim
libp2p/standard_setup.nim

Addressing some comments from #519

More exports cleanup

---

libp2p.nim
libp2p/standard_setup.nim

add multi types to exports

---

libp2p/protocols/pubsub/peertable.nim
tests/pubsub/testgossipinternal.nim

[SEC] gossipsub - rebalanceMesh may prune up to D_lo on oversubscription

---

tests/pubsub/testgossipinternal.nim

test rebalanceMesh with low score peers

---

libp2p.nim
libp2p/cid.nim
libp2p/connmanager.nim
libp2p/protocols/protocol.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/standard_setup.nim
libp2p/stream/chronosstream.nim
libp2p/stream/connection.nim
libp2p/switch.nim
libp2p/upgrademngrs/muxedupgrade.nim
libp2p/upgrademngrs/upgrade.nim
libp2p/utils/semaphore.nim
tests/pubsub/testgossipinternal.nim
tests/pubsub/testgossipsub.nim
tests/testconnmngr.nim
tests/testsemaphore.nim
tests/testswitch.nim
tests/testtransport.nim

This needs an approval from someone to be mergeable due to branch rules. @sinkingsugar

Merge master to unstable

---

tests/pubsub/testgossipinternal.nim

[SEC] gossipsub - handleGraft/handlePrune recommendations & notes

---

libp2p/crypto/crypto.nim
tests/testswitch.nim

Debt: cleanup warnings #426

---

tests/pubsub/testgossipsub.nim

[SEC] gossipsub - a peer score is not retained up until expiry if abusive peer unsubscribes

---

libp2p/protocols/pubsub/gossipsub/behavior.nim
tests/pubsub/testgossipinternal.nim

[SEC] gossipsub - handleIHAVE/handleIWANT recommendations & notes

---

libp2p/muxers/mplex/lpchannel.nim
libp2p/muxers/mplex/mplex.nim
libp2p/protocols/pubsub/gossipsub/behavior.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/protocols/secure/secure.nim
libp2p/stream/connection.nim
libp2p/switch.nim
tests/pubsub/testgossipinternal.nim

This PR solves very critical issues in gossipsub, specifically related to incoming connections and peers quality.

Gossipsub fixes and Initiator flagging fixes

---

libp2p/protocols/pubsub/gossipsub/behavior.nim
libp2p/protocols/pubsub/gossipsub/types.nim

as pointed out by @arnetheduck , current metrics were broken.

Consolidate metrics collection for mesh

---

libp2p/cid.nim
libp2p/connmanager.nim
libp2p/daemon/daemonapi.nim
libp2p/multiaddress.nim
libp2p/multibase.nim
libp2p/multicodec.nim
libp2p/multihash.nim
libp2p/muxers/mplex/lpchannel.nim
libp2p/protocols/pubsub/floodsub.nim
libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/gossipsub/behavior.nim
libp2p/protocols/pubsub/gossipsub/scoring.nim
libp2p/protocols/pubsub/mcache.nim
libp2p/protocols/pubsub/peertable.nim
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/protocols/pubsub/timedcache.nim
libp2p/stream/bufferstream.nim
libp2p/stream/chronosstream.nim
libp2p/stream/lpstream.nim
libp2p/switch.nim
libp2p/utility.nim
tests/pubsub/testgossipinternal.nim

* fix accumulating peer score
* fix missing exception handling
* remove unnecessary initHashSet/initTable calls
* simplify peer stats management
* clean up tests a little
* fix some missing raises annotations

fix peer score accumulation

---

libp2p/connmanager.nim

* no need to init orderedset
* array more simple than table

simplify connmanager

---

libp2p/protocols/identify.nim
tests/testidentify.nim

closes #48 
Draft because I haven't tested it with another libp2p implementation to check compability.
Could use a few more tests

Identify Push

---

docs/tutorial/directchat/second.nim
docs/tutorial/second.nim
examples/directchat.nim
examples/go-daemon/bootstrap.nim
examples/go-daemon/chat.nim
tests/testidentify.nim
tests/testmultistream.nim
tests/testnoise.nim
tests/testping.nim
tests/testtransport.nim

Remove asynccheck

---

docs/api/libp2p/daemonapi.md

Corrected filename and directory names in the daemonapi.md﻿

Correct some instructions in the daemonapi.md

---

tests/testnative.nim
tests/testping.nim

And "fix" the testping
The cancellation will eventually be tested by #611

Add missing test to testnative

---

libp2p/multiaddress.nim
libp2p/multicodec.nim
libp2p/routing_record.nim
libp2p/signed_envelope.nim
tests/testnative.nim
tests/testrouting_record.nim
tests/testsigned_envelope.nim

Signed envelopes and routing records

---

examples/directchat.nim

When closing a connection of clientA(using the command “/disconnect”), the connection is then closed on clientA’s side. However, the connection remained open on clientB and clientB could continue sending message to clientA and clientA would receive those messages.
This PR listens for a closing connection on clientB, then also closes clientB’s connection.

fix (directchat): auto disconnect self once conn closed

---

libp2p/muxers/mplex/lpchannel.nim
libp2p/protocols/secure/noise.nim
libp2p/stream/chronosstream.nim

avoids several copies of the various message buffers being kept alive
for the lifetime of the future

fast path for writes

---

libp2p/protocols/pubsub/gossipsub.nim
tests/asyncunit.nim
tests/testdaemon.nim

Closes #679
First dumb version, each message processing is asyncSpawn. Probably good enough?

Gossipsub: process messages concurrently

---

.pinned
examples/directchat.nim
libp2p.nimble
libp2p/connmanager.nim
libp2p/daemon/daemonapi.nim
libp2p/errors.nim
libp2p/nameresolving/dnsresolver.nim
libp2p/protocols/ping.nim
tests/commontransport.nim
tests/helpers.nim
tests/testmultistream.nim
tests/testnoise.nim
tests/testwstransport.nim

closes https://github.com/status-im/nim-libp2p/issues/637
Enable strict exception tracking for chronos, and fixes where it broke
I may update the DNS library instead of handling it here

Chronos strict exception tracking

---

libp2p/protocols/pubsub/pubsub.nim
tests/pubsub/testgossipinternal.nim
tests/pubsub/testmcache.nim
tests/pubsub/testmessage.nim

1. tests: invert expect message logic
2. export pubsub_errors for backward compatibility

fixes from #688

---

.pinned
libp2p/transports/wstransport.nim

Merge https://github.com/status-im/nim-websock/pull/102 first

WS Accept timeout

---

libp2p/crypto/chacha20poly1305.nim
libp2p/crypto/curve25519.nim
tests/testcrypto.nim

Fix https://github.com/status-im/nim-libp2p/issues/712

encrypt and decrypt empty sequences

---

libp2p/peerinfo.nim
libp2p/protocols/identify.nim
libp2p/switch.nim
tests/testidentify.nim
tests/testpeerinfo.nim

First quick version to fix for waku, I'll do a better follow up (required for codex)

Update SPR when the PeerInfo changes

---

libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/gossipsub/behavior.nim
libp2p/protocols/pubsub/gossipsub/types.nim
tests/pubsub/testgossipsub.nim
tests/pubsub/utils.nim

Gossipsub: Put Peer Exchange behind a flag

---

libp2p/protocols/pubsub/gossipsub/behavior.nim

closes https://github.com/status-im/nim-libp2p/issues/705
cc @arnetheduck, if you have a test bench already setup, could you check if this is now optimized enough?

Optimize rebalanceMesh

---

libp2p/muxers/mplex/lpchannel.nim
libp2p/protocols/secure/secure.nim
libp2p/stream/bufferstream.nim

And fix a regression introduced by https://github.com/status-im/nim-libp2p/pull/659
Trying to write to a closed mplex channel closed the entire connection

Handle more cancellations

---

.github/workflows/doc.yml
README.md
examples/README.md
examples/tutorial_1_connect.md
examples/tutorial_2_customproto.md
libp2p.nim
mkdocs.yml

Follow up of #716
Using material for mkdocs to generate a nicer website:
https://status-im.github.io/nim-libp2p/docs/
(Note that the "reference" link will work once this hits master)

Documentation site

---

libp2p/connmanager.nim
libp2p/dialer.nim
libp2p/switch.nim
tests/testconnmngr.nim
tests/testswitch.nim

Simpler API which avoids the "ConnProvider" callback
Saner IMO

ConnManager connection tracking refacto

---

libp2p/protocols/pubsub/gossipsub.nim
tests/pubsub/testgossipsub.nim
tests/pubsub/testgossipsub2.nim

Mostly relevant in test, but also nice to have in other scenarios
Also, various speedups in the gossipsub CI

Gossipsub: Rebalance mesh immediately when peer sub/unsub

---

libp2p/multiaddress.nim
libp2p/multicodec.nim
tests/testmultiaddress.nim

Add onion3 multiaddr support

---

examples/circuitrelay.nim
libp2p/builders.nim
libp2p/protocols/connectivity/autonat.nim
libp2p/protocols/connectivity/relay/client.nim
libp2p/protocols/connectivity/relay/messages.nim
libp2p/protocols/connectivity/relay/rconn.nim
libp2p/protocols/connectivity/relay/relay.nim
libp2p/protocols/connectivity/relay/rtransport.nim
libp2p/protocols/connectivity/relay/utils.nim
tests/commoninterop.nim
tests/testautonat.nim
tests/testinterop.nim
tests/testrelayv1.nim
tests/testrelayv2.nim

Trying to keep things tidy, since in the end we will probably have >5 connectivity protocols

Move relay & autonat to connectivity folder

---

libp2p/dialer.nim
libp2p/multiaddress.nim
libp2p/nameresolving/nameresolver.nim
tests/testnameresolve.nim
tests/testnoise.nim
tests/testswitch.nim

Also tries multiples address on dial failure
ref https://github.com/status-im/nim-libp2p/pull/615#issuecomment-958851810

Better dnsaddr resolving

---

.github/workflows/multi_nim.yml
.pinned
libp2p/protocols/pubsub/pubsub.nim
libp2p/protocols/secure/secure.nim
libp2p/stream/lpstream.nim
libp2p/upgrademngrs/upgrade.nim

Waiting on:
- https://github.com/ba0f3/dnsclient.nim/pull/12
- https://github.com/status-im/nim-websock/pull/130
- https://github.com/status-im/nim-stew/pull/146
Removing 1.4 as we don't support it

Fix daily CI

---

README.md
libp2p.nimble

Supersedes https://github.com/status-im/nim-libp2p/pull/493

Version 1.0.0

---

libp2p/daemon/daemonapi.nim
libp2p/protobuf/minprotobuf.nim
tests/testminprotobuf.nim

Mostly related to - https://github.com/status-im/nim-codex/issues/308, but useful in general.

Allow passing max message size

---

libp2p/transports/wstransport.nim

See: https://github.com/status-im/nwaku/issues/1186
A peer can lock us up here

WS leak: handleRequest can hang

---

libp2p/protocols/pubsub/rpc/protobuf.nim
tests/pubsub/testfloodsub.nim

They are currently capped to 4mb

Fix: big messages in pubsub

---

libp2p/dial.nim
libp2p/dialer.nim
libp2p/switch.nim
tests/testswitch.nim

Allow connect with known PeerId in MA

---

libp2p/varint.nim

Should fix this https://github.com/status-im/nim-libp2p/actions/runs/3655094186/jobs/6176112803

Fix devel 32bits

---

libp2p/connmanager.nim
libp2p/dialer.nim
tests/testconnmngr.nim

The proc `getOutgoingSlot` doesn't use anything async.

Remove unnecessary async

---

libp2p/protocols/connectivity/autonat/client.nim
libp2p/protocols/connectivity/autonat/server.nim
libp2p/protocols/connectivity/autonat/service.nim
libp2p/utils/future.nim
tests/testautonat.nim
tests/testfuture.nim
tests/testnative.nim

There's also some change in the log levels. The motivation is to provide more useful information when running the system in debug. Currently, most of the logs use trace and it is unrealistic to run the system in a non-local environment with this log level due to the huge amount of data created.

Dialing addrs concurrently in autonat

---

tests/testrelayv2.nim

Should fix some rare race conditions that could happen in the CI (here for example https://github.com/status-im/nim-libp2p/actions/runs/4164524254/jobs/7206275505#step:8:5175)

Fix testrelay

---

libp2p/routing_record.nim
tests/testrouting_record.nim

Related to:
* https://github.com/waku-org/nwaku/issues/1768

Fail only if all addresses in PeerRecord are invalid

---

.github/workflows/bumper.yml

```
Your branch is up to date with 'origin/unstable'.
nothing to commit, working tree clean
Error: Process completed with exit code 1.
```
Can happen if we start the job manually

Bumper: fix case where target is up to date

---

libp2p/transports/tcptransport.nim

Follow up https://github.com/status-im/nim-libp2p/pull/916

TCP transport: handle getObservedAddr errors

---

libp2p/switch.nim
libp2p/transports/tcptransport.nim

#916 introduced a regression: https://github.com/status-im/nim-libp2p/pull/916/files#diff-aec912568e88e9cbe6b7e748b2212b5f6dd37b004669bc284476755f657fd85eL267
Also, small cleanup

Fix #916 regression causing accept loop lockup

---

.github/workflows/interop.yml

Ref https://github.com/libp2p/test-plans/pull/308
Closes https://github.com/status-im/nim-libp2p/issues/955

Update interop CI name

---

.github/workflows/doc.yml

Use nim 1.6.x as nimble install_pinned does not work with nim 2.0.0 and nimble 0.14.2

fix: doc workflow

---

libp2p.nimble

Remove the range because apparently nimble does not handle it properly

Remove unittest2 range

---

libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim

Fix compilation issue when `libp2p_expensive_metrics` is enabled.

fix: compilation issue when `libp2p_expensive_metrics` is enabled.

---

libp2p/protocols/pubsub/gossipsub.nim
libp2p/protocols/pubsub/pubsubpeer.nim

Metric definition also needs to be moved to the right file.

fix: more metrics issues when libp2p_expensive_metrics is enabled

---

.gitignore
tests/helpers.nim

Attempt to fix flaky tests by increasing the check timeout.

tests(flaky): Increase check timeouts

---

README.md
examples/go-daemon/daemonapi.md
scripts/build_p2pd.sh

Improve documentation related to go-libp2p-daemon building, and nim version.

docs(general): Improve docs

---

libp2p/errors.nim

This fixes allFuturesThrowing that is failing with a compilation issue on daily after chronos new release.

fix: allFuturesThrowing compilation issue on daily

---

.github/workflows/interop.yml
tests/transport-interop/Dockerfile
tests/transport-interop/main.nim
tests/transport-interop/version.json

closes https://github.com/status-im/nim-libp2p/issues/1013

fix: move transport interop tests to nim-libp2p repo

---

libp2p/muxers/yamux/yamux.nim

Using `notin` and then `[header.streamId]` twice results in the table `m.flushed` to be searched three times. The code can be optimized to only a single lookup using `tables.withValue`.

avoid triple lookup in `m.flushed` yamux table

---

libp2p/connmanager.nim

When connecting to a peer, there are a couple aspects to be fixed:
- Triple lookup with `notin`, `[]` and `mgetOrPut`, improved with `withValue`.
- Empty `newSeq[Muxer]()` is skipped, now directly uses `@[muxer]`
- `assert` changed to `doAssert`

clean up triple lookup and avoid `KeyError` when adding muxer

---

.github/workflows/doc.yml

fix(CI): generate website job

---

libp2p/services/wildcardresolverservice.nim
tests/testnative.nim
tests/testwildcardresolverservice.nim

Fixes https://github.com/vacp2p/nim-libp2p/issues/1147

fix: support ipv6 dual stack

---

libp2p.nimble

This PR's commit is planned to be tagged as v1.8.0

chore(version): update libp2p.nimble to 1.8.0

---

libp2p/utils/future.nim

part of https://github.com/vacp2p/nim-libp2p/issues/962 effort.

chore: list raised exceptions in `utils` module

---

libp2p/connmanager.nim
libp2p/utils/semaphore.nim

specifies raised exceptions in `ConnManager` type
part of https://github.com/vacp2p/nim-libp2p/issues/962 effort.

chore(connmanager): specify raised exceptions

---

examples/go-daemon/chat.nim
libp2p/protocols/connectivity/autonat/client.nim
tests/helpers.nim
tests/pubsub/testgossipsub.nim

chore: specify exceptions in try statement

---

.github/workflows/dependencies.yml

chore: use token per repo in autobump task

---

libp2p/transports/tls/certificate.nim
tests/transports/tls/testcertificate.nim

- fix for https://github.com/vacp2p/nim-libp2p/pull/1292#discussion_r2003552185
- use named tuple

chore(certificate): cosmetics

---

libp2p/transports/tls/certificate.c
libp2p/transports/tls/certificate.h
libp2p/transports/tls/certificate.nim
libp2p/transports/tls/certificate_ffi.nim
tests/transports/tls/testcertificate.nim

- adds date verification
- adds parameters for certificate valid from/to times

feat(certificate): add date verification

---

libp2p/transports/quictransport.nim
libp2p/transports/tls/certificate.nim
tests/testquic.nim
tests/transports/tls/testcertificate.nim

- add test case for quic where client and server have invalid certificate
- small refactor

chore(quic): add tests with invalid certs

---

.gitignore

this will help us by ignoring auto generate test binaries to appear in commits.

chore(git): ignore auto generated test binaries

---

libp2p/transports/tls/certificate.c
libp2p/transports/tls/certificate.h
libp2p/transports/tls/certificate.nim
libp2p/transports/tls/certificate_ffi.nim
tests/transports/tls/testcertificate.nim

Add certificate signing request generation in `transports/tls/certificate.c`

feat(cert): add certificate signing request (CSR) generation

---

.pinned
libp2p.nimble

Requires:
- https://github.com/vacp2p/nim-quic/pull/71

chore: bump quic

---

README.md
examples/go-daemon/daemonapi.md
scripts/build_p2pd.sh

- Cleaned up Development section in `README`
- Moved `daemonapi.md`'s "Getting Started" chat example section to "Getting Started" in the `README`
- Added `-v` (verbose) and `-f` (force build) flags to `build_p2pd.sh`
Fixes #1375

chore(readme): improve README's development section

---

tests/pubsub/testgossipsubgossip.nim
tests/pubsub/testgossipsubheartbeat.nim
tests/pubsub/testgossipsubmeshmanagement.nim

Changes:
- updates for recent flaky tests

test(gossipsub): flaky tests

---

interop/transport/main.nim
libp2p/builders.nim
tests/commoninterop.nim

feat: `withWsTransport`

---

tests/pubsub/testgossipsubscoring.nim
tests/pubsub/utils.nim

Changes:
- refactor `GossipSub Scoring` tests to latest conventions before adding new tests in this area
- extract common utilities

test(gossipsub): refactor and unify scoring tests

---

libp2p/peeridauth/client.nim
libp2p/peeridauth/mockclient.nim
tests/testpeeridauth.nim
tests/testpeeridauth_integration.nim

Add mocked peeridauth client for unit testing

chore(peeridauth): add mocked client

---

libp2p/autotls/acme/api.nim
libp2p/autotls/acme/client.nim
libp2p/autotls/acme/mockapi.nim
libp2p/autotls/acme/utils.nim
tests/testautotls.nim
tests/testautotls_integration.nim

This is what will be directly used by AutoTLS

chore(acme): add ACMEClient to hold information about an ACME account

---

tests/testperf.nim

- add quic test
- test `perf with exception` will be executed for mplex and yamux

chore(perf): add quic test

---

libp2p/protocols/secure/secure.nim

* utilizing `ZeroQueue` in `readOnce` to eliminated allocations imposed by `StreamSeq.add`

refactor(secure): utilize ZeroQueue

---

.github/workflows/daily_common.yml

CI run: https://github.com/vacp2p/nim-libp2p/actions/runs/16032349564/job/45235784271

fix(ci): move testintegration to new step

---

libp2p/switch.nim

chore: add info to error

---

tests/pubsub/testgossipsub.nim

Changes:
- add unit tests for `GossipSub` `gossipsub`:
- `rpcHandler - message already seen - valid message dropped when ID already in seenMsgs`
- `rpcHandler - message validation ignore drops message`
- `rpcHandler - message validation accept and successful relay`
- `onTopicSubscription - subscribe removes topic from fanout and rebalances mesh`
- `onTopicSubscription - unsubscribe removes topic from mesh`

test(gossipsub): gossipsub unit tests 2

---

libp2p.nimble
libp2p/protocols/pubsub/bandwidth.nim
libp2p/protocols/pubsub/gossipsub/types.nim
libp2p/protocols/pubsub/pubsubpeer.nim
libp2p/protocols/pubsub/rpc/messages.nim
libp2p/protocols/pubsub/rpc/protobuf.nim

Code extracted from https://github.com/vacp2p/nim-libp2p/pull/1448 for easier reviewal.
This focuses only on the new attributes being added as well as changes on the protobuf encoding
Actual behavior is to be done on separate PR
cc: @ufarooqstatus

feat(gossipsub1.4): adding new attributes and protobuffers

---

libp2p/autotls/acme/client.nim
libp2p/autotls/acme/utils.nim
libp2p/autotls/service.nim
libp2p/builders.nim

Fixes error described in #1548

fix: autotls related imports

---

tests/testquic.nim

should have been part of  #1576

chore(quic): add close session test

---

.github/workflows/daily_amd64.yml
.github/workflows/daily_common.yml
.github/workflows/daily_i386.yml
.github/workflows/daily_nimbus.yml

Daily CI run [here](https://github.com/vacp2p/nim-libp2p/actions/runs/16650249139/job/47120777049?pr=1571)

ci: add nimbus compilation daily test

---

libp2p/protocols/mix/seqno_generator.nim
libp2p/protocols/mix/tag_manager.nim
tests/mix/testseqnogenerator.nim
tests/mix/testtagmanager.nim
tests/testnative.nim

Adds these files from mix repo and their tests

feat(mix): sequence number generator and tag manager

---

libp2p/protocols/mix/entry_connection.nim
libp2p/protocols/mix/exit_layer.nim
libp2p/protocols/mix/mix_metrics.nim
libp2p/protocols/mix/mix_protocol.nim
libp2p/protocols/mix/serialization.nim
libp2p/protocols/mix/sphinx.nim
tests/mix/testserialization.nim

PR is a bit large already and complex to split it up further. I'll include the tests in the next PR that will include also the logic for reply path

feat(mix): mix_protocol and entry connection

---

libp2p/protocols/connectivity/autonatv2/server.nim

We were only closing the stream but not the actual connection

fix(autonatv2): close dialback connection

---

.pinned
examples/tutorial_3_protobuf.nim
examples/tutorial_4_gossipsub.nim
libp2p.nimble

Merge this after the version of nim-websock has been bumped in https://github.com/status-im/nim-websock/pull/176

fix: update nim-stew version

---

libp2p/autotls/acme/client.nim
libp2p/autotls/service.nim
libp2p/autotls/utils.nim
tests/testautotls_config.nim

feat(autotls): add configurable options to AutotlsConfig
